services:
  docfx-site:
    build: .
    restart: unless-stopped

  tunnel:
    container_name: wasdk-docs-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
