### YamlMime:ManagedReference
items:
- uid: ABI.Microsoft.Windows.ApplicationModel.Resources
  commentId: N:ABI.Microsoft.Windows.ApplicationModel.Resources
  id: ABI.Microsoft.Windows.ApplicationModel.Resources
  children:
  - ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceContextMethods
  - ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceManagerMethods
  langs:
  - csharp
  - vb
  name: ABI.Microsoft.Windows.ApplicationModel.Resources
  nameWithType: ABI.Microsoft.Windows.ApplicationModel.Resources
  fullName: ABI.Microsoft.Windows.ApplicationModel.Resources
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceContextMethods
  commentId: T:ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceContextMethods
  href: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceContextMethods.html
  name: IResourceContextMethods
  nameWithType: IResourceContextMethods
  fullName: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceContextMethods
- uid: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceManagerMethods
  commentId: T:ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceManagerMethods
  href: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceManagerMethods.html
  name: IResourceManagerMethods
  nameWithType: IResourceManagerMethods
  fullName: ABI.Microsoft.Windows.ApplicationModel.Resources.IResourceManagerMethods
