### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  commentId: T:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  id: UniversalBackgroundTaskContract
  parent: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  children: []
  langs:
  - csharp
  - vb
  name: UniversalBackgroundTaskContract
  nameWithType: UniversalBackgroundTaskContract
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: UniversalBackgroundTaskContract
    path: ../src/Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.cs
    startLine: 144
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  syntax:
    content: >-
      [ContractVersion(65536)]

      public enum UniversalBackgroundTaskContract
    content.vb: >-
      <ContractVersion(65536)>

      Public Enum UniversalBackgroundTaskContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "65536"
references:
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  commentId: N:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  nameWithType: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
    name: UniversalBGTask
    href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
    name: UniversalBGTask
    href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.html
