### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  id: MrtCoreContract
  parent: Microsoft.Windows.ApplicationModel.Resources
  children: []
  langs:
  - csharp
  - vb
  name: MrtCoreContract
  nameWithType: MrtCoreContract
  fullName: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: MrtCoreContract
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 178
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: >-
      [ContractVersion(131072)]

      public enum MrtCoreContract
    content.vb: >-
      <ContractVersion(131072)>

      Public Enum MrtCoreContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "131072"
references:
- uid: Microsoft.Windows.ApplicationModel.Resources
  commentId: N:Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Resources
  nameWithType: Microsoft.Windows.ApplicationModel.Resources
  fullName: Microsoft.Windows.ApplicationModel.Resources
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
