### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Storage.ApplicationDataContract
  commentId: T:Microsoft.Windows.Storage.ApplicationDataContract
  id: ApplicationDataContract
  parent: Microsoft.Windows.Storage
  children: []
  langs:
  - csharp
  - vb
  name: ApplicationDataContract
  nameWithType: ApplicationDataContract
  fullName: Microsoft.Windows.Storage.ApplicationDataContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationDataContract
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 266
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: >-
      [ContractVersion(131072)]

      public enum ApplicationDataContract
    content.vb: >-
      <ContractVersion(131072)>

      Public Enum ApplicationDataContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "131072"
references:
- uid: Microsoft.Windows.Storage
  commentId: N:Microsoft.Windows.Storage
  href: Microsoft.html
  name: Microsoft.Windows.Storage
  nameWithType: Microsoft.Windows.Storage
  fullName: Microsoft.Windows.Storage
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
