### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  id: VersionInfoContract
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  children: []
  langs:
  - csharp
  - vb
  name: VersionInfoContract
  nameWithType: VersionInfoContract
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: VersionInfoContract
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 590
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: >-
      [ContractVersion(65536)]

      public enum VersionInfoContract
    content.vb: >-
      <ContractVersion(65536)>

      Public Enum VersionInfoContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "65536"
references:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  commentId: N:Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  nameWithType: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
