### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption
  commentId: T:Microsoft.Windows.Management.Deployment.StubPackageOption
  id: StubPackageOption
  parent: Microsoft.Windows.Management.Deployment
  children:
  - Microsoft.Windows.Management.Deployment.StubPackageOption.Default
  - Microsoft.Windows.Management.Deployment.StubPackageOption.InstallFull
  - Microsoft.Windows.Management.Deployment.StubPackageOption.InstallStub
  - Microsoft.Windows.Management.Deployment.StubPackageOption.UsePreference
  langs:
  - csharp
  - vb
  name: StubPackageOption
  nameWithType: StubPackageOption
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: StubPackageOption
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 2158
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Management.Deployment")]

      [WinRTExposedType(typeof(EnumTypeDetails<StubPackageOption>))]

      [ContractVersion(typeof(PackageDeploymentContract), 65536)]

      public enum StubPackageOption
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Management.Deployment")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of StubPackageOption)))>

      <ContractVersion(GetType(PackageDeploymentContract), 65536)>

      Public Enum StubPackageOption
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Management.Deployment
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Management.Deployment.StubPackageOption}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption.Default
  commentId: F:Microsoft.Windows.Management.Deployment.StubPackageOption.Default
  id: Default
  parent: Microsoft.Windows.Management.Deployment.StubPackageOption
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: StubPackageOption.Default
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption.Default
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Default
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 2161
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: Default = 0
    return:
      type: Microsoft.Windows.Management.Deployment.StubPackageOption
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption.InstallFull
  commentId: F:Microsoft.Windows.Management.Deployment.StubPackageOption.InstallFull
  id: InstallFull
  parent: Microsoft.Windows.Management.Deployment.StubPackageOption
  langs:
  - csharp
  - vb
  name: InstallFull
  nameWithType: StubPackageOption.InstallFull
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption.InstallFull
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: InstallFull
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 2162
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: InstallFull = 1
    return:
      type: Microsoft.Windows.Management.Deployment.StubPackageOption
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption.InstallStub
  commentId: F:Microsoft.Windows.Management.Deployment.StubPackageOption.InstallStub
  id: InstallStub
  parent: Microsoft.Windows.Management.Deployment.StubPackageOption
  langs:
  - csharp
  - vb
  name: InstallStub
  nameWithType: StubPackageOption.InstallStub
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption.InstallStub
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: InstallStub
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 2163
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: InstallStub = 2
    return:
      type: Microsoft.Windows.Management.Deployment.StubPackageOption
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption.UsePreference
  commentId: F:Microsoft.Windows.Management.Deployment.StubPackageOption.UsePreference
  id: UsePreference
  parent: Microsoft.Windows.Management.Deployment.StubPackageOption
  langs:
  - csharp
  - vb
  name: UsePreference
  nameWithType: StubPackageOption.UsePreference
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption.UsePreference
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: UsePreference
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 2164
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: UsePreference = 3
    return:
      type: Microsoft.Windows.Management.Deployment.StubPackageOption
references:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption
  commentId: T:Microsoft.Windows.Management.Deployment.StubPackageOption
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.StubPackageOption.html
  name: StubPackageOption
  nameWithType: StubPackageOption
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption
