### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  commentId: T:Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  id: ApplicationDataCreateDisposition
  parent: Microsoft.Windows.Storage
  children:
  - Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Always
  - Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Existing
  langs:
  - csharp
  - vb
  name: ApplicationDataCreateDisposition
  nameWithType: ApplicationDataCreateDisposition
  fullName: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationDataCreateDisposition
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 270
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Storage")]

      [WinRTExposedType(typeof(EnumTypeDetails<ApplicationDataCreateDisposition>))]

      [ContractVersion(typeof(ApplicationDataContract), 65536)]

      public enum ApplicationDataCreateDisposition
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Storage")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ApplicationDataCreateDisposition)))>

      <ContractVersion(GetType(ApplicationDataContract), 65536)>

      Public Enum ApplicationDataCreateDisposition
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Storage
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Storage.ApplicationDataCreateDisposition}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Storage.ApplicationDataContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Always
  commentId: F:Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Always
  id: Always
  parent: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  langs:
  - csharp
  - vb
  name: Always
  nameWithType: ApplicationDataCreateDisposition.Always
  fullName: Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Always
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Always
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 273
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: Always = 0
    return:
      type: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
- uid: Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Existing
  commentId: F:Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Existing
  id: Existing
  parent: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  langs:
  - csharp
  - vb
  name: Existing
  nameWithType: ApplicationDataCreateDisposition.Existing
  fullName: Microsoft.Windows.Storage.ApplicationDataCreateDisposition.Existing
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Existing
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 274
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: Existing = 1
    return:
      type: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
references:
- uid: Microsoft.Windows.Storage
  commentId: N:Microsoft.Windows.Storage
  href: Microsoft.html
  name: Microsoft.Windows.Storage
  nameWithType: Microsoft.Windows.Storage
  fullName: Microsoft.Windows.Storage
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
- uid: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  commentId: T:Microsoft.Windows.Storage.ApplicationDataCreateDisposition
  parent: Microsoft.Windows.Storage
  href: Microsoft.Windows.Storage.ApplicationDataCreateDisposition.html
  name: ApplicationDataCreateDisposition
  nameWithType: ApplicationDataCreateDisposition
  fullName: Microsoft.Windows.Storage.ApplicationDataCreateDisposition
