### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  id: PackageDeploymentStatus
  parent: Microsoft.Windows.Management.Deployment
  children:
  - Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedFailure
  - Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedSuccess
  - Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.InProgress
  langs:
  - csharp
  - vb
  name: PackageDeploymentStatus
  nameWithType: PackageDeploymentStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageDeploymentStatus
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 906
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Management.Deployment")]

      [WinRTExposedType(typeof(EnumTypeDetails<PackageDeploymentStatus>))]

      [ContractVersion(typeof(PackageDeploymentContract), 65536)]

      public enum PackageDeploymentStatus
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Management.Deployment")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of PackageDeploymentStatus)))>

      <ContractVersion(GetType(PackageDeploymentContract), 65536)>

      Public Enum PackageDeploymentStatus
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Management.Deployment
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Management.Deployment.PackageDeploymentStatus}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.InProgress
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.InProgress
  id: InProgress
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  langs:
  - csharp
  - vb
  name: InProgress
  nameWithType: PackageDeploymentStatus.InProgress
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.InProgress
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: InProgress
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 909
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: InProgress = 0
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedSuccess
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedSuccess
  id: CompletedSuccess
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  langs:
  - csharp
  - vb
  name: CompletedSuccess
  nameWithType: PackageDeploymentStatus.CompletedSuccess
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedSuccess
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: CompletedSuccess
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 910
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: CompletedSuccess = 1
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedFailure
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedFailure
  id: CompletedFailure
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  langs:
  - csharp
  - vb
  name: CompletedFailure
  nameWithType: PackageDeploymentStatus.CompletedFailure
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.CompletedFailure
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: CompletedFailure
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 911
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: CompletedFailure = 2
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
references:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.html
  name: PackageDeploymentStatus
  nameWithType: PackageDeploymentStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
