### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency
  commentId: N:Microsoft.Windows.ApplicationModel.DynamicDependency
  id: Microsoft.Windows.ApplicationModel.DynamicDependency
  children:
  - Microsoft.Windows.ApplicationModel.DynamicDependency.AddPackageDependencyOptions
  - Microsoft.Windows.ApplicationModel.DynamicDependency.CreatePackageDependencyOptions
  - Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContext
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyLifetimeArtifactKind
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.ApplicationModel.DynamicDependency
  nameWithType: Microsoft.Windows.ApplicationModel.DynamicDependency
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.AddPackageDependencyOptions
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.AddPackageDependencyOptions
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.AddPackageDependencyOptions.html
  name: AddPackageDependencyOptions
  nameWithType: AddPackageDependencyOptions
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.AddPackageDependencyOptions
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.CreatePackageDependencyOptions
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.CreatePackageDependencyOptions
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.CreatePackageDependencyOptions.html
  name: CreatePackageDependencyOptions
  nameWithType: CreatePackageDependencyOptions
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.CreatePackageDependencyOptions
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract.html
  name: DynamicDependencyContract
  nameWithType: DynamicDependencyContract
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency.html
  name: PackageDependency
  nameWithType: PackageDependency
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContext
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContext
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContext.html
  name: PackageDependencyContext
  nameWithType: PackageDependencyContext
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContext
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId.html
  name: PackageDependencyContextId
  nameWithType: PackageDependencyContextId
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyLifetimeArtifactKind
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyLifetimeArtifactKind
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyLifetimeArtifactKind.html
  name: PackageDependencyLifetimeArtifactKind
  nameWithType: PackageDependencyLifetimeArtifactKind
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyLifetimeArtifactKind
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.html
  name: PackageDependencyProcessorArchitectures
  nameWithType: PackageDependencyProcessorArchitectures
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank.html
  name: PackageDependencyRank
  nameWithType: PackageDependencyRank
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency
  commentId: N:Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.DynamicDependency
  nameWithType: Microsoft.Windows.ApplicationModel.DynamicDependency
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
