### YamlMime:ManagedReference
items:
- uid: Microsoft.UI.Input.GestureSettings
  commentId: T:Microsoft.UI.Input.GestureSettings
  id: GestureSettings
  parent: Microsoft.UI.Input
  children:
  - Microsoft.UI.Input.GestureSettings.CrossSlide
  - Microsoft.UI.Input.GestureSettings.DoubleTap
  - Microsoft.UI.Input.GestureSettings.Drag
  - Microsoft.UI.Input.GestureSettings.Hold
  - Microsoft.UI.Input.GestureSettings.HoldWithMouse
  - Microsoft.UI.Input.GestureSettings.ManipulationMultipleFingerPanning
  - Microsoft.UI.Input.GestureSettings.ManipulationRotate
  - Microsoft.UI.Input.GestureSettings.ManipulationRotateInertia
  - Microsoft.UI.Input.GestureSettings.ManipulationScale
  - Microsoft.UI.Input.GestureSettings.ManipulationScaleInertia
  - Microsoft.UI.Input.GestureSettings.ManipulationTranslateInertia
  - Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsX
  - Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsY
  - Microsoft.UI.Input.GestureSettings.ManipulationTranslateX
  - Microsoft.UI.Input.GestureSettings.ManipulationTranslateY
  - Microsoft.UI.Input.GestureSettings.None
  - Microsoft.UI.Input.GestureSettings.RightTap
  - Microsoft.UI.Input.GestureSettings.Tap
  langs:
  - csharp
  - vb
  name: GestureSettings
  nameWithType: GestureSettings
  fullName: Microsoft.UI.Input.GestureSettings
  type: Enum
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: GestureSettings
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1179
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: >-
      [Flags]

      [WindowsRuntimeType("Microsoft.UI")]

      [WinRTExposedType(typeof(EnumTypeDetails<GestureSettings>))]

      [ContractVersion(typeof(WindowsAppSDKContract), 65536)]

      public enum GestureSettings : uint
    content.vb: >-
      <Flags>

      <WindowsRuntimeType("Microsoft.UI")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of GestureSettings)))>

      <ContractVersion(GetType(WindowsAppSDKContract), 65536)>

      Public Enum GestureSettings As UInteger
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.UI
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.UI.Input.GestureSettings}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Foundation.WindowsAppSDKContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.UI.Input.GestureSettings.None
  commentId: F:Microsoft.UI.Input.GestureSettings.None
  id: None
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: None
  nameWithType: GestureSettings.None
  fullName: Microsoft.UI.Input.GestureSettings.None
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: None
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1183
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: None = 0
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.Tap
  commentId: F:Microsoft.UI.Input.GestureSettings.Tap
  id: Tap
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: Tap
  nameWithType: GestureSettings.Tap
  fullName: Microsoft.UI.Input.GestureSettings.Tap
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Tap
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1184
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: Tap = 1
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.DoubleTap
  commentId: F:Microsoft.UI.Input.GestureSettings.DoubleTap
  id: DoubleTap
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: DoubleTap
  nameWithType: GestureSettings.DoubleTap
  fullName: Microsoft.UI.Input.GestureSettings.DoubleTap
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: DoubleTap
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1185
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: DoubleTap = 2
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.Hold
  commentId: F:Microsoft.UI.Input.GestureSettings.Hold
  id: Hold
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: Hold
  nameWithType: GestureSettings.Hold
  fullName: Microsoft.UI.Input.GestureSettings.Hold
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Hold
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1186
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: Hold = 4
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.HoldWithMouse
  commentId: F:Microsoft.UI.Input.GestureSettings.HoldWithMouse
  id: HoldWithMouse
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: HoldWithMouse
  nameWithType: GestureSettings.HoldWithMouse
  fullName: Microsoft.UI.Input.GestureSettings.HoldWithMouse
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: HoldWithMouse
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1187
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: HoldWithMouse = 8
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.RightTap
  commentId: F:Microsoft.UI.Input.GestureSettings.RightTap
  id: RightTap
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: RightTap
  nameWithType: GestureSettings.RightTap
  fullName: Microsoft.UI.Input.GestureSettings.RightTap
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: RightTap
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1188
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: RightTap = 16
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.Drag
  commentId: F:Microsoft.UI.Input.GestureSettings.Drag
  id: Drag
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: Drag
  nameWithType: GestureSettings.Drag
  fullName: Microsoft.UI.Input.GestureSettings.Drag
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Drag
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1189
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: Drag = 32
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationTranslateX
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationTranslateX
  id: ManipulationTranslateX
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationTranslateX
  nameWithType: GestureSettings.ManipulationTranslateX
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationTranslateX
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationTranslateX
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1190
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationTranslateX = 64
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationTranslateY
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationTranslateY
  id: ManipulationTranslateY
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationTranslateY
  nameWithType: GestureSettings.ManipulationTranslateY
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationTranslateY
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationTranslateY
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1191
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationTranslateY = 128
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsX
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsX
  id: ManipulationTranslateRailsX
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationTranslateRailsX
  nameWithType: GestureSettings.ManipulationTranslateRailsX
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsX
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationTranslateRailsX
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1192
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationTranslateRailsX = 256
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsY
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsY
  id: ManipulationTranslateRailsY
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationTranslateRailsY
  nameWithType: GestureSettings.ManipulationTranslateRailsY
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationTranslateRailsY
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationTranslateRailsY
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1193
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationTranslateRailsY = 512
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationRotate
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationRotate
  id: ManipulationRotate
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationRotate
  nameWithType: GestureSettings.ManipulationRotate
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationRotate
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationRotate
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1194
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationRotate = 1024
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationScale
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationScale
  id: ManipulationScale
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationScale
  nameWithType: GestureSettings.ManipulationScale
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationScale
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationScale
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1195
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationScale = 2048
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationTranslateInertia
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationTranslateInertia
  id: ManipulationTranslateInertia
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationTranslateInertia
  nameWithType: GestureSettings.ManipulationTranslateInertia
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationTranslateInertia
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationTranslateInertia
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1196
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationTranslateInertia = 4096
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationRotateInertia
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationRotateInertia
  id: ManipulationRotateInertia
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationRotateInertia
  nameWithType: GestureSettings.ManipulationRotateInertia
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationRotateInertia
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationRotateInertia
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1197
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationRotateInertia = 8192
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationScaleInertia
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationScaleInertia
  id: ManipulationScaleInertia
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationScaleInertia
  nameWithType: GestureSettings.ManipulationScaleInertia
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationScaleInertia
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationScaleInertia
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1198
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationScaleInertia = 16384
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.CrossSlide
  commentId: F:Microsoft.UI.Input.GestureSettings.CrossSlide
  id: CrossSlide
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: CrossSlide
  nameWithType: GestureSettings.CrossSlide
  fullName: Microsoft.UI.Input.GestureSettings.CrossSlide
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: CrossSlide
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1199
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: CrossSlide = 32768
    return:
      type: Microsoft.UI.Input.GestureSettings
- uid: Microsoft.UI.Input.GestureSettings.ManipulationMultipleFingerPanning
  commentId: F:Microsoft.UI.Input.GestureSettings.ManipulationMultipleFingerPanning
  id: ManipulationMultipleFingerPanning
  parent: Microsoft.UI.Input.GestureSettings
  langs:
  - csharp
  - vb
  name: ManipulationMultipleFingerPanning
  nameWithType: GestureSettings.ManipulationMultipleFingerPanning
  fullName: Microsoft.UI.Input.GestureSettings.ManipulationMultipleFingerPanning
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Input.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ManipulationMultipleFingerPanning
    path: ../src/Microsoft.UI.Input.cs
    startLine: 1200
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Input
  syntax:
    content: ManipulationMultipleFingerPanning = 65536
    return:
      type: Microsoft.UI.Input.GestureSettings
references:
- uid: Microsoft.UI.Input
  commentId: N:Microsoft.UI.Input
  href: Microsoft.html
  name: Microsoft.UI.Input
  nameWithType: Microsoft.UI.Input
  fullName: Microsoft.UI.Input
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Input
    name: Input
    href: Microsoft.UI.Input.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Input
    name: Input
    href: Microsoft.UI.Input.html
- uid: Microsoft.UI.Input.GestureSettings
  commentId: T:Microsoft.UI.Input.GestureSettings
  parent: Microsoft.UI.Input
  href: Microsoft.UI.Input.GestureSettings.html
  name: GestureSettings
  nameWithType: GestureSettings
  fullName: Microsoft.UI.Input.GestureSettings
