### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Resources
  commentId: N:Microsoft.Windows.ApplicationModel.Resources
  id: Microsoft.Windows.ApplicationModel.Resources
  children:
  - Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  - Microsoft.Windows.ApplicationModel.Resources.IResourceManager
  - Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName
  - Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  - Microsoft.Windows.ApplicationModel.Resources.ResourceContext
  - Microsoft.Windows.ApplicationModel.Resources.ResourceLoader
  - Microsoft.Windows.ApplicationModel.Resources.ResourceManager
  - Microsoft.Windows.ApplicationModel.Resources.ResourceMap
  - Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.ApplicationModel.Resources
  nameWithType: Microsoft.Windows.ApplicationModel.Resources
  fullName: Microsoft.Windows.ApplicationModel.Resources
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.html
  name: IResourceContext
  nameWithType: IResourceContext
  fullName: Microsoft.Windows.ApplicationModel.Resources.IResourceContext
- uid: Microsoft.Windows.ApplicationModel.Resources.IResourceManager
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.IResourceManager
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.IResourceManager.html
  name: IResourceManager
  nameWithType: IResourceManager
  fullName: Microsoft.Windows.ApplicationModel.Resources.IResourceManager
- uid: Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName
  href: Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName.html
  name: KnownResourceQualifierName
  nameWithType: KnownResourceQualifierName
  fullName: Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName
- uid: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract.html
  name: MrtCoreContract
  nameWithType: MrtCoreContract
  fullName: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate.html
  name: ResourceCandidate
  nameWithType: ResourceCandidate
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.html
  name: ResourceCandidateKind
  nameWithType: ResourceCandidateKind
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceContext
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceContext
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceContext.html
  name: ResourceContext
  nameWithType: ResourceContext
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceContext
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceLoader
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceLoader
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceLoader.html
  name: ResourceLoader
  nameWithType: ResourceLoader
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceLoader
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceManager
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceManager
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceManager.html
  name: ResourceManager
  nameWithType: ResourceManager
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceManager
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceMap
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceMap
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceMap.html
  name: ResourceMap
  nameWithType: ResourceMap
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceMap
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs.html
  name: ResourceNotFoundEventArgs
  nameWithType: ResourceNotFoundEventArgs
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs
- uid: Microsoft.Windows.ApplicationModel.Resources
  commentId: N:Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Resources
  nameWithType: Microsoft.Windows.ApplicationModel.Resources
  fullName: Microsoft.Windows.ApplicationModel.Resources
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
