### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  id: PackageReadyOrNewerAvailableStatus
  parent: Microsoft.Windows.Management.Deployment
  children:
  - Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NewerAvailable
  - Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NotReady
  - Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.Ready
  langs:
  - csharp
  - vb
  name: PackageReadyOrNewerAvailableStatus
  nameWithType: PackageReadyOrNewerAvailableStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageReadyOrNewerAvailableStatus
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 913
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Management.Deployment")]

      [WinRTExposedType(typeof(EnumTypeDetails<PackageReadyOrNewerAvailableStatus>))]

      [ContractVersion(typeof(PackageDeploymentContract), 131072)]

      public enum PackageReadyOrNewerAvailableStatus
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Management.Deployment")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of PackageReadyOrNewerAvailableStatus)))>

      <ContractVersion(GetType(PackageDeploymentContract), 131072)>

      Public Enum PackageReadyOrNewerAvailableStatus
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Management.Deployment
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
    - type: System.UInt32
      value: "131072"
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NotReady
  commentId: F:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NotReady
  id: NotReady
  parent: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  langs:
  - csharp
  - vb
  name: NotReady
  nameWithType: PackageReadyOrNewerAvailableStatus.NotReady
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NotReady
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: NotReady
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 916
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: NotReady = 0
    return:
      type: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.Ready
  commentId: F:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.Ready
  id: Ready
  parent: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  langs:
  - csharp
  - vb
  name: Ready
  nameWithType: PackageReadyOrNewerAvailableStatus.Ready
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.Ready
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Ready
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 917
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: Ready = 1
    return:
      type: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NewerAvailable
  commentId: F:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NewerAvailable
  id: NewerAvailable
  parent: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  langs:
  - csharp
  - vb
  name: NewerAvailable
  nameWithType: PackageReadyOrNewerAvailableStatus.NewerAvailable
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.NewerAvailable
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: NewerAvailable
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 918
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: NewerAvailable = 2
    return:
      type: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
references:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.html
  name: PackageReadyOrNewerAvailableStatus
  nameWithType: PackageReadyOrNewerAvailableStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
