### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  id: ResourceCandidateKind
  parent: Microsoft.Windows.ApplicationModel.Resources
  children:
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.EmbeddedData
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.FilePath
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.String
  - Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.Unknown
  langs:
  - csharp
  - vb
  name: ResourceCandidateKind
  nameWithType: ResourceCandidateKind
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ResourceCandidateKind
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 354
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.ApplicationModel.Resources")]

      [WinRTExposedType(typeof(EnumTypeDetails<ResourceCandidateKind>))]

      [ContractVersion(typeof(MrtCoreContract), 65536)]

      public enum ResourceCandidateKind
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.ApplicationModel.Resources")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ResourceCandidateKind)))>

      <ContractVersion(GetType(MrtCoreContract), 65536)>

      Public Enum ResourceCandidateKind
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.ApplicationModel.Resources
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.Unknown
  commentId: F:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.Unknown
  id: Unknown
  parent: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ResourceCandidateKind.Unknown
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.Unknown
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Unknown
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 357
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.String
  commentId: F:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.String
  id: String
  parent: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  langs:
  - csharp
  - vb
  name: String
  nameWithType: ResourceCandidateKind.String
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.String
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: String
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 358
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: String = 1
    return:
      type: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.FilePath
  commentId: F:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.FilePath
  id: FilePath
  parent: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  langs:
  - csharp
  - vb
  name: FilePath
  nameWithType: ResourceCandidateKind.FilePath
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.FilePath
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: FilePath
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 359
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: FilePath = 2
    return:
      type: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.EmbeddedData
  commentId: F:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.EmbeddedData
  id: EmbeddedData
  parent: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  langs:
  - csharp
  - vb
  name: EmbeddedData
  nameWithType: ResourceCandidateKind.EmbeddedData
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.EmbeddedData
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: EmbeddedData
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 360
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: EmbeddedData = 3
    return:
      type: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
references:
- uid: Microsoft.Windows.ApplicationModel.Resources
  commentId: N:Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Resources
  nameWithType: Microsoft.Windows.ApplicationModel.Resources
  fullName: Microsoft.Windows.ApplicationModel.Resources
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
- uid: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
  parent: Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind.html
  name: ResourceCandidateKind
  nameWithType: ResourceCandidateKind
  fullName: Microsoft.Windows.ApplicationModel.Resources.ResourceCandidateKind
