### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  id: DynamicDependencyContract
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  children: []
  langs:
  - csharp
  - vb
  name: DynamicDependencyContract
  nameWithType: DynamicDependencyContract
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: DynamicDependencyContract
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 263
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: >-
      [ContractVersion(131072)]

      public enum DynamicDependencyContract
    content.vb: >-
      <ContractVersion(131072)>

      Public Enum DynamicDependencyContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "131072"
references:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency
  commentId: N:Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.DynamicDependency
  nameWithType: Microsoft.Windows.ApplicationModel.DynamicDependency
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
