### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  commentId: T:Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  id: IResourceContext
  parent: Microsoft.Windows.ApplicationModel.Resources
  children:
  - Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
  langs:
  - csharp
  - vb
  name: IResourceContext
  nameWithType: IResourceContext
  fullName: Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  type: Interface
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: IResourceContext
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.ApplicationModel.Resources")]

      [Guid("96FB48DC-F77D-55FF-AF12-34861E3D4939")]

      [WindowsRuntimeHelperType(typeof(IResourceContext))]

      [ContractVersion(typeof(MrtCoreContract), 65536)]

      public interface IResourceContext
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.ApplicationModel.Resources")>

      <Guid("96FB48DC-F77D-55FF-AF12-34861E3D4939")>

      <WindowsRuntimeHelperType(GetType(IResourceContext))>

      <ContractVersion(GetType(MrtCoreContract), 65536)>

      Public Interface IResourceContext
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.ApplicationModel.Resources
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 96FB48DC-F77D-55FF-AF12-34861E3D4939
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.ApplicationModel.Resources.MrtCoreContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
  commentId: P:Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
  id: QualifierValues
  parent: Microsoft.Windows.ApplicationModel.Resources.IResourceContext
  langs:
  - csharp
  - vb
  name: QualifierValues
  nameWithType: IResourceContext.QualifierValues
  fullName: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
  type: Property
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.Resources.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: QualifierValues
    path: ../src/Microsoft.Windows.ApplicationModel.Resources.cs
    startLine: 63
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.Resources
  syntax:
    content: IDictionary<string, string> QualifierValues { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
    content.vb: ReadOnly Property QualifierValues As IDictionary(Of String, String)
  overload: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues*
references:
- uid: Microsoft.Windows.ApplicationModel.Resources
  commentId: N:Microsoft.Windows.ApplicationModel.Resources
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Resources
  nameWithType: Microsoft.Windows.ApplicationModel.Resources
  fullName: Microsoft.Windows.ApplicationModel.Resources
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Resources
    name: Resources
    href: Microsoft.Windows.ApplicationModel.Resources.html
- uid: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues*
  commentId: Overload:Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
  href: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.html#Microsoft_Windows_ApplicationModel_Resources_IResourceContext_QualifierValues
  name: QualifierValues
  nameWithType: IResourceContext.QualifierValues
  fullName: Microsoft.Windows.ApplicationModel.Resources.IResourceContext.QualifierValues
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  commentId: T:System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<string, string>
  nameWithType: IDictionary<string, string>
  fullName: System.Collections.Generic.IDictionary<string, string>
  nameWithType.vb: IDictionary(Of String, String)
  fullName.vb: System.Collections.Generic.IDictionary(Of String, String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IDictionary`2
  commentId: T:System.Collections.Generic.IDictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<TKey, TValue>
  nameWithType: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  nameWithType.vb: IDictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
