### YamlMime:ManagedReference
items:
- uid: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  commentId: T:Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  id: ApplicationRequiresPointerMode
  parent: Microsoft.UI.Xaml
  children:
  - Microsoft.UI.Xaml.ApplicationRequiresPointerMode.Auto
  - Microsoft.UI.Xaml.ApplicationRequiresPointerMode.WhenRequested
  langs:
  - csharp
  - vb
  name: ApplicationRequiresPointerMode
  nameWithType: ApplicationRequiresPointerMode
  fullName: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  type: Enum
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationRequiresPointerMode
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 521
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.UI.Xaml")]

      [WinRTExposedType(typeof(EnumTypeDetails<ApplicationRequiresPointerMode>))]

      [ContractVersion(typeof(WinUIContract), 65536)]

      public enum ApplicationRequiresPointerMode
    content.vb: >-
      <WindowsRuntimeType("Microsoft.UI.Xaml")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ApplicationRequiresPointerMode)))>

      <ContractVersion(GetType(WinUIContract), 65536)>

      Public Enum ApplicationRequiresPointerMode
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.UI.Xaml
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.UI.Xaml.ApplicationRequiresPointerMode}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.UI.Xaml.WinUIContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.UI.Xaml.ApplicationRequiresPointerMode.Auto
  commentId: F:Microsoft.UI.Xaml.ApplicationRequiresPointerMode.Auto
  id: Auto
  parent: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  langs:
  - csharp
  - vb
  name: Auto
  nameWithType: ApplicationRequiresPointerMode.Auto
  fullName: Microsoft.UI.Xaml.ApplicationRequiresPointerMode.Auto
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Auto
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 524
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: Auto = 0
    return:
      type: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
- uid: Microsoft.UI.Xaml.ApplicationRequiresPointerMode.WhenRequested
  commentId: F:Microsoft.UI.Xaml.ApplicationRequiresPointerMode.WhenRequested
  id: WhenRequested
  parent: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  langs:
  - csharp
  - vb
  name: WhenRequested
  nameWithType: ApplicationRequiresPointerMode.WhenRequested
  fullName: Microsoft.UI.Xaml.ApplicationRequiresPointerMode.WhenRequested
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: WhenRequested
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 525
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: WhenRequested = 1
    return:
      type: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
references:
- uid: Microsoft.UI.Xaml
  commentId: N:Microsoft.UI.Xaml
  href: Microsoft.html
  name: Microsoft.UI.Xaml
  nameWithType: Microsoft.UI.Xaml
  fullName: Microsoft.UI.Xaml
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
- uid: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  commentId: T:Microsoft.UI.Xaml.ApplicationRequiresPointerMode
  parent: Microsoft.UI.Xaml
  href: Microsoft.UI.Xaml.ApplicationRequiresPointerMode.html
  name: ApplicationRequiresPointerMode
  nameWithType: ApplicationRequiresPointerMode
  fullName: Microsoft.UI.Xaml.ApplicationRequiresPointerMode
