### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  id: PackageDeploymentFeature
  parent: Microsoft.Windows.Management.Deployment
  children:
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.IsPackageReadyOrNewerAvailable
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.PackageUriScheme_ms_uup
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ProvisionPackage_Framework
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RemovePackageByUri
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RepairPackage
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ResetPackage
  langs:
  - csharp
  - vb
  name: PackageDeploymentFeature
  nameWithType: PackageDeploymentFeature
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageDeploymentFeature
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 585
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Management.Deployment")]

      [WinRTExposedType(typeof(EnumTypeDetails<PackageDeploymentFeature>))]

      [ContractVersion(typeof(PackageDeploymentContract), 131072)]

      public enum PackageDeploymentFeature
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Management.Deployment")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of PackageDeploymentFeature)))>

      <ContractVersion(GetType(PackageDeploymentContract), 131072)>

      Public Enum PackageDeploymentFeature
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Management.Deployment
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Management.Deployment.PackageDeploymentFeature}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
    - type: System.UInt32
      value: "131072"
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.PackageUriScheme_ms_uup
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.PackageUriScheme_ms_uup
  id: PackageUriScheme_ms_uup
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: PackageUriScheme_ms_uup
  nameWithType: PackageDeploymentFeature.PackageUriScheme_ms_uup
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.PackageUriScheme_ms_uup
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageUriScheme_ms_uup
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 588
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: PackageUriScheme_ms_uup = 1
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.IsPackageReadyOrNewerAvailable
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.IsPackageReadyOrNewerAvailable
  id: IsPackageReadyOrNewerAvailable
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: IsPackageReadyOrNewerAvailable
  nameWithType: PackageDeploymentFeature.IsPackageReadyOrNewerAvailable
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.IsPackageReadyOrNewerAvailable
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: IsPackageReadyOrNewerAvailable
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 589
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: IsPackageReadyOrNewerAvailable = 2
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RemovePackageByUri
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RemovePackageByUri
  id: RemovePackageByUri
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: RemovePackageByUri
  nameWithType: PackageDeploymentFeature.RemovePackageByUri
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RemovePackageByUri
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: RemovePackageByUri
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 590
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: RemovePackageByUri = 3
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ResetPackage
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ResetPackage
  id: ResetPackage
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: ResetPackage
  nameWithType: PackageDeploymentFeature.ResetPackage
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ResetPackage
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ResetPackage
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 591
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: ResetPackage = 4
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RepairPackage
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RepairPackage
  id: RepairPackage
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: RepairPackage
  nameWithType: PackageDeploymentFeature.RepairPackage
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.RepairPackage
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: RepairPackage
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 592
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: RepairPackage = 5
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ProvisionPackage_Framework
  commentId: F:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ProvisionPackage_Framework
  id: ProvisionPackage_Framework
  parent: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  langs:
  - csharp
  - vb
  name: ProvisionPackage_Framework
  nameWithType: PackageDeploymentFeature.ProvisionPackage_Framework
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.ProvisionPackage_Framework
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ProvisionPackage_Framework
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 593
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: ProvisionPackage_Framework = 6
    return:
      type: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
references:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.html
  name: PackageDeploymentFeature
  nameWithType: PackageDeploymentFeature
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
