### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  id: PackageDeploymentContract
  parent: Microsoft.Windows.Management.Deployment
  children: []
  langs:
  - csharp
  - vb
  name: PackageDeploymentContract
  nameWithType: PackageDeploymentContract
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Management.Deployment.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageDeploymentContract
    path: ../src/Microsoft.Windows.Management.Deployment.cs
    startLine: 581
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Management.Deployment
  syntax:
    content: >-
      [ContractVersion(131072)]

      public enum PackageDeploymentContract
    content.vb: >-
      <ContractVersion(131072)>

      Public Enum PackageDeploymentContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "131072"
references:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
