### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Storage.ApplicationDataLocality
  commentId: T:Microsoft.Windows.Storage.ApplicationDataLocality
  id: ApplicationDataLocality
  parent: Microsoft.Windows.Storage
  children:
  - Microsoft.Windows.Storage.ApplicationDataLocality.Local
  - Microsoft.Windows.Storage.ApplicationDataLocality.LocalCache
  - Microsoft.Windows.Storage.ApplicationDataLocality.Machine
  - Microsoft.Windows.Storage.ApplicationDataLocality.SharedLocal
  - Microsoft.Windows.Storage.ApplicationDataLocality.Temporary
  langs:
  - csharp
  - vb
  name: ApplicationDataLocality
  nameWithType: ApplicationDataLocality
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationDataLocality
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 276
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.Storage")]

      [WinRTExposedType(typeof(EnumTypeDetails<ApplicationDataLocality>))]

      [ContractVersion(typeof(ApplicationDataContract), 65536)]

      public enum ApplicationDataLocality
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.Storage")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ApplicationDataLocality)))>

      <ContractVersion(GetType(ApplicationDataContract), 65536)>

      Public Enum ApplicationDataLocality
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.Storage
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.Storage.ApplicationDataLocality}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.Storage.ApplicationDataContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.Storage.ApplicationDataLocality.Local
  commentId: F:Microsoft.Windows.Storage.ApplicationDataLocality.Local
  id: Local
  parent: Microsoft.Windows.Storage.ApplicationDataLocality
  langs:
  - csharp
  - vb
  name: Local
  nameWithType: ApplicationDataLocality.Local
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality.Local
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Local
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 279
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: Local = 0
    return:
      type: Microsoft.Windows.Storage.ApplicationDataLocality
- uid: Microsoft.Windows.Storage.ApplicationDataLocality.LocalCache
  commentId: F:Microsoft.Windows.Storage.ApplicationDataLocality.LocalCache
  id: LocalCache
  parent: Microsoft.Windows.Storage.ApplicationDataLocality
  langs:
  - csharp
  - vb
  name: LocalCache
  nameWithType: ApplicationDataLocality.LocalCache
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality.LocalCache
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: LocalCache
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 280
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: LocalCache = 3
    return:
      type: Microsoft.Windows.Storage.ApplicationDataLocality
- uid: Microsoft.Windows.Storage.ApplicationDataLocality.SharedLocal
  commentId: F:Microsoft.Windows.Storage.ApplicationDataLocality.SharedLocal
  id: SharedLocal
  parent: Microsoft.Windows.Storage.ApplicationDataLocality
  langs:
  - csharp
  - vb
  name: SharedLocal
  nameWithType: ApplicationDataLocality.SharedLocal
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality.SharedLocal
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: SharedLocal
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 281
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: SharedLocal = 4
    return:
      type: Microsoft.Windows.Storage.ApplicationDataLocality
- uid: Microsoft.Windows.Storage.ApplicationDataLocality.Temporary
  commentId: F:Microsoft.Windows.Storage.ApplicationDataLocality.Temporary
  id: Temporary
  parent: Microsoft.Windows.Storage.ApplicationDataLocality
  langs:
  - csharp
  - vb
  name: Temporary
  nameWithType: ApplicationDataLocality.Temporary
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality.Temporary
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Temporary
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 282
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: Temporary = 2
    return:
      type: Microsoft.Windows.Storage.ApplicationDataLocality
- uid: Microsoft.Windows.Storage.ApplicationDataLocality.Machine
  commentId: F:Microsoft.Windows.Storage.ApplicationDataLocality.Machine
  id: Machine
  parent: Microsoft.Windows.Storage.ApplicationDataLocality
  langs:
  - csharp
  - vb
  name: Machine
  nameWithType: ApplicationDataLocality.Machine
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality.Machine
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.Storage.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Machine
    path: ../src/Microsoft.Windows.Storage.cs
    startLine: 283
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.Storage
  syntax:
    content: Machine = 1000
    return:
      type: Microsoft.Windows.Storage.ApplicationDataLocality
references:
- uid: Microsoft.Windows.Storage
  commentId: N:Microsoft.Windows.Storage
  href: Microsoft.html
  name: Microsoft.Windows.Storage
  nameWithType: Microsoft.Windows.Storage
  fullName: Microsoft.Windows.Storage
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Storage
    name: Storage
    href: Microsoft.Windows.Storage.html
- uid: Microsoft.Windows.Storage.ApplicationDataLocality
  commentId: T:Microsoft.Windows.Storage.ApplicationDataLocality
  parent: Microsoft.Windows.Storage
  href: Microsoft.Windows.Storage.ApplicationDataLocality.html
  name: ApplicationDataLocality
  nameWithType: ApplicationDataLocality
  fullName: Microsoft.Windows.Storage.ApplicationDataLocality
