### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  id: PackageDependencyProcessorArchitectures
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  children:
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm64
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Neutral
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.None
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X64
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86
  - Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86OnArm64
  langs:
  - csharp
  - vb
  name: PackageDependencyProcessorArchitectures
  nameWithType: PackageDependencyProcessorArchitectures
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageDependencyProcessorArchitectures
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 618
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: >-
      [Flags]

      [WindowsRuntimeType("Microsoft.Windows.ApplicationModel.DynamicDependency")]

      [WinRTExposedType(typeof(EnumTypeDetails<PackageDependencyProcessorArchitectures>))]

      [ContractVersion(typeof(DynamicDependencyContract), 65536)]

      public enum PackageDependencyProcessorArchitectures : uint
    content.vb: >-
      <Flags>

      <WindowsRuntimeType("Microsoft.Windows.ApplicationModel.DynamicDependency")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of PackageDependencyProcessorArchitectures)))>

      <ContractVersion(GetType(DynamicDependencyContract), 65536)>

      Public Enum PackageDependencyProcessorArchitectures As UInteger
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.ApplicationModel.DynamicDependency
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.None
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.None
  id: None
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: None
  nameWithType: PackageDependencyProcessorArchitectures.None
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.None
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: None
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 622
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: None = 0
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Neutral
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Neutral
  id: Neutral
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: Neutral
  nameWithType: PackageDependencyProcessorArchitectures.Neutral
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Neutral
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Neutral
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 623
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: Neutral = 1
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86
  id: X86
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: X86
  nameWithType: PackageDependencyProcessorArchitectures.X86
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: X86
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 624
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: X86 = 2
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X64
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X64
  id: X64
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: X64
  nameWithType: PackageDependencyProcessorArchitectures.X64
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X64
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: X64
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 625
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: X64 = 4
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm
  id: Arm
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: Arm
  nameWithType: PackageDependencyProcessorArchitectures.Arm
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Arm
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 626
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: Arm = 8
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm64
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm64
  id: Arm64
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: Arm64
  nameWithType: PackageDependencyProcessorArchitectures.Arm64
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.Arm64
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Arm64
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 627
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: Arm64 = 16
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86OnArm64
  commentId: F:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86OnArm64
  id: X86OnArm64
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  langs:
  - csharp
  - vb
  name: X86OnArm64
  nameWithType: PackageDependencyProcessorArchitectures.X86OnArm64
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.X86OnArm64
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: X86OnArm64
    path: ../src/Microsoft.Windows.ApplicationModel.DynamicDependency.cs
    startLine: 628
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.DynamicDependency
  syntax:
    content: X86OnArm64 = 32
    return:
      type: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
references:
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency
  commentId: N:Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.DynamicDependency
  nameWithType: Microsoft.Windows.ApplicationModel.DynamicDependency
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.DynamicDependency
    name: DynamicDependency
    href: Microsoft.Windows.ApplicationModel.DynamicDependency.html
- uid: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  commentId: T:Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
  parent: Microsoft.Windows.ApplicationModel.DynamicDependency
  href: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures.html
  name: PackageDependencyProcessorArchitectures
  nameWithType: PackageDependencyProcessorArchitectures
  fullName: Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyProcessorArchitectures
