### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  id: DeploymentStatus
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  children:
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Ok
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallFailed
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallRequired
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Unknown
  langs:
  - csharp
  - vb
  name: DeploymentStatus
  nameWithType: DeploymentStatus
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: DeploymentStatus
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 332
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.ApplicationModel.WindowsAppRuntime")]

      [WinRTExposedType(typeof(EnumTypeDetails<DeploymentStatus>))]

      [ContractVersion(typeof(DeploymentContract), 65536)]

      public enum DeploymentStatus
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.ApplicationModel.WindowsAppRuntime")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of DeploymentStatus)))>

      <ContractVersion(GetType(DeploymentContract), 65536)>

      Public Enum DeploymentStatus
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Unknown
  commentId: F:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Unknown
  id: Unknown
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: DeploymentStatus.Unknown
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Unknown
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Unknown
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 335
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Ok
  commentId: F:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Ok
  id: Ok
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Ok
  nameWithType: DeploymentStatus.Ok
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.Ok
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Ok
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 336
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: Ok = 1
    return:
      type: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallRequired
  commentId: F:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallRequired
  id: PackageInstallRequired
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  langs:
  - csharp
  - vb
  name: PackageInstallRequired
  nameWithType: DeploymentStatus.PackageInstallRequired
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallRequired
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageInstallRequired
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 337
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: PackageInstallRequired = 2
    return:
      type: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallFailed
  commentId: F:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallFailed
  id: PackageInstallFailed
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  langs:
  - csharp
  - vb
  name: PackageInstallFailed
  nameWithType: DeploymentStatus.PackageInstallFailed
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.PackageInstallFailed
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: PackageInstallFailed
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 338
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: PackageInstallFailed = 3
    return:
      type: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
references:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  commentId: N:Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  nameWithType: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.html
  name: DeploymentStatus
  nameWithType: DeploymentStatus
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
