### YamlMime:ManagedReference
items:
- uid: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  commentId: T:Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  id: ApplicationHighContrastAdjustment
  parent: Microsoft.UI.Xaml
  children:
  - Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.Auto
  - Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.None
  langs:
  - csharp
  - vb
  name: ApplicationHighContrastAdjustment
  nameWithType: ApplicationHighContrastAdjustment
  fullName: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  type: Enum
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationHighContrastAdjustment
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 438
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: >-
      [Flags]

      [WindowsRuntimeType("Microsoft.UI.Xaml")]

      [WinRTExposedType(typeof(EnumTypeDetails<ApplicationHighContrastAdjustment>))]

      [ContractVersion(typeof(WinUIContract), 65536)]

      public enum ApplicationHighContrastAdjustment : uint
    content.vb: >-
      <Flags>

      <WindowsRuntimeType("Microsoft.UI.Xaml")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ApplicationHighContrastAdjustment)))>

      <ContractVersion(GetType(WinUIContract), 65536)>

      Public Enum ApplicationHighContrastAdjustment As UInteger
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.UI.Xaml
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.UI.Xaml.ApplicationHighContrastAdjustment}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.UI.Xaml.WinUIContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.None
  commentId: F:Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.None
  id: None
  parent: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ApplicationHighContrastAdjustment.None
  fullName: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.None
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: None
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 442
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: None = 0
    return:
      type: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
- uid: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.Auto
  commentId: F:Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.Auto
  id: Auto
  parent: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  langs:
  - csharp
  - vb
  name: Auto
  nameWithType: ApplicationHighContrastAdjustment.Auto
  fullName: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.Auto
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Auto
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 443
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: Auto = 4294967295
    return:
      type: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
references:
- uid: Microsoft.UI.Xaml
  commentId: N:Microsoft.UI.Xaml
  href: Microsoft.html
  name: Microsoft.UI.Xaml
  nameWithType: Microsoft.UI.Xaml
  fullName: Microsoft.UI.Xaml
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
- uid: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  commentId: T:Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
  parent: Microsoft.UI.Xaml
  href: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment.html
  name: ApplicationHighContrastAdjustment
  nameWithType: ApplicationHighContrastAdjustment
  fullName: Microsoft.UI.Xaml.ApplicationHighContrastAdjustment
