### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  commentId: N:Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  id: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  children:
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.WindowsAppRuntimeVersion
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  nameWithType: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract.html
  name: DeploymentContract
  nameWithType: DeploymentContract
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentContract
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions.html
  name: DeploymentInitializeOptions
  nameWithType: DeploymentInitializeOptions
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.html
  name: DeploymentManager
  nameWithType: DeploymentManager
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult.html
  name: DeploymentResult
  nameWithType: DeploymentResult
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus.html
  name: DeploymentStatus
  nameWithType: DeploymentStatus
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo.html
  name: ReleaseInfo
  nameWithType: ReleaseInfo
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.html
  name: RuntimeCompatibilityChange
  nameWithType: RuntimeCompatibilityChange
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract.html
  name: RuntimeCompatibilityContract
  nameWithType: RuntimeCompatibilityContract
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions.html
  name: RuntimeCompatibilityOptions
  nameWithType: RuntimeCompatibilityOptions
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo.html
  name: RuntimeInfo
  nameWithType: RuntimeInfo
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract.html
  name: VersionInfoContract
  nameWithType: VersionInfoContract
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.VersionInfoContract
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.WindowsAppRuntimeVersion
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.WindowsAppRuntimeVersion
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.WindowsAppRuntimeVersion.html
  name: WindowsAppRuntimeVersion
  nameWithType: WindowsAppRuntimeVersion
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.WindowsAppRuntimeVersion
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  commentId: N:Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  nameWithType: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
