### YamlMime:ManagedReference
items:
- uid: Microsoft.UI.Xaml.ApplicationTheme
  commentId: T:Microsoft.UI.Xaml.ApplicationTheme
  id: ApplicationTheme
  parent: Microsoft.UI.Xaml
  children:
  - Microsoft.UI.Xaml.ApplicationTheme.Dark
  - Microsoft.UI.Xaml.ApplicationTheme.Light
  langs:
  - csharp
  - vb
  name: ApplicationTheme
  nameWithType: ApplicationTheme
  fullName: Microsoft.UI.Xaml.ApplicationTheme
  type: Enum
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: ApplicationTheme
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 527
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.UI.Xaml")]

      [WinRTExposedType(typeof(EnumTypeDetails<ApplicationTheme>))]

      [ContractVersion(typeof(WinUIContract), 65536)]

      public enum ApplicationTheme
    content.vb: >-
      <WindowsRuntimeType("Microsoft.UI.Xaml")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of ApplicationTheme)))>

      <ContractVersion(GetType(WinUIContract), 65536)>

      Public Enum ApplicationTheme
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.UI.Xaml
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.UI.Xaml.ApplicationTheme}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.UI.Xaml.WinUIContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.UI.Xaml.ApplicationTheme.Light
  commentId: F:Microsoft.UI.Xaml.ApplicationTheme.Light
  id: Light
  parent: Microsoft.UI.Xaml.ApplicationTheme
  langs:
  - csharp
  - vb
  name: Light
  nameWithType: ApplicationTheme.Light
  fullName: Microsoft.UI.Xaml.ApplicationTheme.Light
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Light
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 530
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: Light = 0
    return:
      type: Microsoft.UI.Xaml.ApplicationTheme
- uid: Microsoft.UI.Xaml.ApplicationTheme.Dark
  commentId: F:Microsoft.UI.Xaml.ApplicationTheme.Dark
  id: Dark
  parent: Microsoft.UI.Xaml.ApplicationTheme
  langs:
  - csharp
  - vb
  name: Dark
  nameWithType: ApplicationTheme.Dark
  fullName: Microsoft.UI.Xaml.ApplicationTheme.Dark
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Xaml.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Dark
    path: ../src/Microsoft.UI.Xaml.cs
    startLine: 531
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Xaml
  syntax:
    content: Dark = 1
    return:
      type: Microsoft.UI.Xaml.ApplicationTheme
references:
- uid: Microsoft.UI.Xaml
  commentId: N:Microsoft.UI.Xaml
  href: Microsoft.html
  name: Microsoft.UI.Xaml
  nameWithType: Microsoft.UI.Xaml
  fullName: Microsoft.UI.Xaml
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Xaml
    name: Xaml
    href: Microsoft.UI.Xaml.html
- uid: Microsoft.UI.Xaml.ApplicationTheme
  commentId: T:Microsoft.UI.Xaml.ApplicationTheme
  parent: Microsoft.UI.Xaml
  href: Microsoft.UI.Xaml.ApplicationTheme.html
  name: ApplicationTheme
  nameWithType: ApplicationTheme
  fullName: Microsoft.UI.Xaml.ApplicationTheme
