### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Background
  commentId: N:Microsoft.Windows.ApplicationModel.Background
  id: Microsoft.Windows.ApplicationModel.Background
  children:
  - Microsoft.Windows.ApplicationModel.Background.BackgroundTaskBuilder
  - Microsoft.Windows.ApplicationModel.Background.BackgroundTaskContract
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.ApplicationModel.Background
  nameWithType: Microsoft.Windows.ApplicationModel.Background
  fullName: Microsoft.Windows.ApplicationModel.Background
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskBuilder
  commentId: T:Microsoft.Windows.ApplicationModel.Background.BackgroundTaskBuilder
  parent: Microsoft.Windows.ApplicationModel.Background
  href: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskBuilder.html
  name: BackgroundTaskBuilder
  nameWithType: BackgroundTaskBuilder
  fullName: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskBuilder
- uid: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskContract
  commentId: T:Microsoft.Windows.ApplicationModel.Background.BackgroundTaskContract
  parent: Microsoft.Windows.ApplicationModel.Background
  href: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskContract.html
  name: BackgroundTaskContract
  nameWithType: BackgroundTaskContract
  fullName: Microsoft.Windows.ApplicationModel.Background.BackgroundTaskContract
- uid: Microsoft.Windows.ApplicationModel.Background
  commentId: N:Microsoft.Windows.ApplicationModel.Background
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Background
  nameWithType: Microsoft.Windows.ApplicationModel.Background
  fullName: Microsoft.Windows.ApplicationModel.Background
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
