### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  commentId: N:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  id: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  children:
  - Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task
  - Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  nameWithType: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task
  commentId: T:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task
  parent: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task.html
  name: Task
  nameWithType: Task
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  commentId: T:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
  parent: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract.html
  name: UniversalBackgroundTaskContract
  nameWithType: UniversalBackgroundTaskContract
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.UniversalBackgroundTaskContract
- uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  commentId: N:Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  nameWithType: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  fullName: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
    name: UniversalBGTask
    href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background
    name: Background
    href: Microsoft.Windows.ApplicationModel.Background.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask
    name: UniversalBGTask
    href: Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.html
