### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  id: RuntimeCompatibilityChange
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  children:
  - Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.None
  langs:
  - csharp
  - vb
  name: RuntimeCompatibilityChange
  nameWithType: RuntimeCompatibilityChange
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: RuntimeCompatibilityChange
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 439
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.Windows.ApplicationModel.WindowsAppRuntime")]

      [WinRTExposedType(typeof(EnumTypeDetails<RuntimeCompatibilityChange>))]

      [ContractVersion(typeof(RuntimeCompatibilityContract), 65536)]

      public enum RuntimeCompatibilityChange
    content.vb: >-
      <WindowsRuntimeType("Microsoft.Windows.ApplicationModel.WindowsAppRuntime")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of RuntimeCompatibilityChange)))>

      <ContractVersion(GetType(RuntimeCompatibilityContract), 65536)>

      Public Enum RuntimeCompatibilityChange
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.None
  commentId: F:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.None
  id: None
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  langs:
  - csharp
  - vb
  name: None
  nameWithType: RuntimeCompatibilityChange.None
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.None
  type: Field
  source:
    remote:
      path: src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: None
    path: ../src/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.cs
    startLine: 442
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  syntax:
    content: None = 0
    return:
      type: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
references:
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  commentId: N:Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.html
  name: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  nameWithType: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel
    name: ApplicationModel
    href: Microsoft.Windows.ApplicationModel.html
  - name: .
  - uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
    name: WindowsAppRuntime
    href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.html
- uid: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  commentId: T:Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
  parent: Microsoft.Windows.ApplicationModel.WindowsAppRuntime
  href: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange.html
  name: RuntimeCompatibilityChange
  nameWithType: RuntimeCompatibilityChange
  fullName: Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityChange
