### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.System.EnvironmentManagerContract
  commentId: T:Microsoft.Windows.System.EnvironmentManagerContract
  id: EnvironmentManagerContract
  parent: Microsoft.Windows.System
  children: []
  langs:
  - csharp
  - vb
  name: EnvironmentManagerContract
  nameWithType: EnvironmentManagerContract
  fullName: Microsoft.Windows.System.EnvironmentManagerContract
  type: Enum
  source:
    remote:
      path: src/Microsoft.Windows.System.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: EnvironmentManagerContract
    path: ../src/Microsoft.Windows.System.cs
    startLine: 154
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.Windows.System
  syntax:
    content: >-
      [ContractVersion(131072)]

      public enum EnvironmentManagerContract
    content.vb: >-
      <ContractVersion(131072)>

      Public Enum EnvironmentManagerContract
  attributes:
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.UInt32)
    arguments:
    - type: System.UInt32
      value: "131072"
references:
- uid: Microsoft.Windows.System
  commentId: N:Microsoft.Windows.System
  href: Microsoft.html
  name: Microsoft.Windows.System
  nameWithType: Microsoft.Windows.System
  fullName: Microsoft.Windows.System
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.System
    name: System
    href: Microsoft.Windows.System.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.System
    name: System
    href: Microsoft.Windows.System.html
