### YamlMime:ManagedReference
items:
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  id: Microsoft.Windows.Management.Deployment
  children:
  - Microsoft.Windows.Management.Deployment.AddPackageOptions
  - Microsoft.Windows.Management.Deployment.EnsureReadyOptions
  - Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  - Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  - Microsoft.Windows.Management.Deployment.PackageDeploymentManager
  - Microsoft.Windows.Management.Deployment.PackageDeploymentProgress
  - Microsoft.Windows.Management.Deployment.PackageDeploymentProgressStatus
  - Microsoft.Windows.Management.Deployment.PackageDeploymentResult
  - Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  - Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  - Microsoft.Windows.Management.Deployment.PackageRuntimeManager
  - Microsoft.Windows.Management.Deployment.PackageSet
  - Microsoft.Windows.Management.Deployment.PackageSetItem
  - Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition
  - Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition
  - Microsoft.Windows.Management.Deployment.PackageVolume
  - Microsoft.Windows.Management.Deployment.ProvisionPackageOptions
  - Microsoft.Windows.Management.Deployment.RegisterPackageOptions
  - Microsoft.Windows.Management.Deployment.RemovePackageOptions
  - Microsoft.Windows.Management.Deployment.StagePackageOptions
  - Microsoft.Windows.Management.Deployment.StubPackageOption
  langs:
  - csharp
  - vb
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  type: Namespace
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
references:
- uid: Microsoft.Windows.Management.Deployment.AddPackageOptions
  commentId: T:Microsoft.Windows.Management.Deployment.AddPackageOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.AddPackageOptions.html
  name: AddPackageOptions
  nameWithType: AddPackageOptions
  fullName: Microsoft.Windows.Management.Deployment.AddPackageOptions
- uid: Microsoft.Windows.Management.Deployment.EnsureReadyOptions
  commentId: T:Microsoft.Windows.Management.Deployment.EnsureReadyOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.EnsureReadyOptions.html
  name: EnsureReadyOptions
  nameWithType: EnsureReadyOptions
  fullName: Microsoft.Windows.Management.Deployment.EnsureReadyOptions
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentContract
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentContract.html
  name: PackageDeploymentContract
  nameWithType: PackageDeploymentContract
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentContract
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature.html
  name: PackageDeploymentFeature
  nameWithType: PackageDeploymentFeature
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentFeature
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentManager
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentManager
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentManager.html
  name: PackageDeploymentManager
  nameWithType: PackageDeploymentManager
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentManager
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentProgress
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentProgress
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentProgress.html
  name: PackageDeploymentProgress
  nameWithType: PackageDeploymentProgress
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentProgress
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentProgressStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentProgressStatus
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentProgressStatus.html
  name: PackageDeploymentProgressStatus
  nameWithType: PackageDeploymentProgressStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentProgressStatus
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentResult
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentResult
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentResult.html
  name: PackageDeploymentResult
  nameWithType: PackageDeploymentResult
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentResult
- uid: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus.html
  name: PackageDeploymentStatus
  nameWithType: PackageDeploymentStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageDeploymentStatus
- uid: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  commentId: T:Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus.html
  name: PackageReadyOrNewerAvailableStatus
  nameWithType: PackageReadyOrNewerAvailableStatus
  fullName: Microsoft.Windows.Management.Deployment.PackageReadyOrNewerAvailableStatus
- uid: Microsoft.Windows.Management.Deployment.PackageRuntimeManager
  commentId: T:Microsoft.Windows.Management.Deployment.PackageRuntimeManager
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageRuntimeManager.html
  name: PackageRuntimeManager
  nameWithType: PackageRuntimeManager
  fullName: Microsoft.Windows.Management.Deployment.PackageRuntimeManager
- uid: Microsoft.Windows.Management.Deployment.PackageSet
  commentId: T:Microsoft.Windows.Management.Deployment.PackageSet
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageSet.html
  name: PackageSet
  nameWithType: PackageSet
  fullName: Microsoft.Windows.Management.Deployment.PackageSet
- uid: Microsoft.Windows.Management.Deployment.PackageSetItem
  commentId: T:Microsoft.Windows.Management.Deployment.PackageSetItem
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageSetItem.html
  name: PackageSetItem
  nameWithType: PackageSetItem
  fullName: Microsoft.Windows.Management.Deployment.PackageSetItem
- uid: Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition
  commentId: T:Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition.html
  name: PackageSetItemRuntimeDisposition
  nameWithType: PackageSetItemRuntimeDisposition
  fullName: Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition
- uid: Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition
  commentId: T:Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition.html
  name: PackageSetRuntimeDisposition
  nameWithType: PackageSetRuntimeDisposition
  fullName: Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition
- uid: Microsoft.Windows.Management.Deployment.PackageVolume
  commentId: T:Microsoft.Windows.Management.Deployment.PackageVolume
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.PackageVolume.html
  name: PackageVolume
  nameWithType: PackageVolume
  fullName: Microsoft.Windows.Management.Deployment.PackageVolume
- uid: Microsoft.Windows.Management.Deployment.ProvisionPackageOptions
  commentId: T:Microsoft.Windows.Management.Deployment.ProvisionPackageOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.ProvisionPackageOptions.html
  name: ProvisionPackageOptions
  nameWithType: ProvisionPackageOptions
  fullName: Microsoft.Windows.Management.Deployment.ProvisionPackageOptions
- uid: Microsoft.Windows.Management.Deployment.RegisterPackageOptions
  commentId: T:Microsoft.Windows.Management.Deployment.RegisterPackageOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.RegisterPackageOptions.html
  name: RegisterPackageOptions
  nameWithType: RegisterPackageOptions
  fullName: Microsoft.Windows.Management.Deployment.RegisterPackageOptions
- uid: Microsoft.Windows.Management.Deployment.RemovePackageOptions
  commentId: T:Microsoft.Windows.Management.Deployment.RemovePackageOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.RemovePackageOptions.html
  name: RemovePackageOptions
  nameWithType: RemovePackageOptions
  fullName: Microsoft.Windows.Management.Deployment.RemovePackageOptions
- uid: Microsoft.Windows.Management.Deployment.StagePackageOptions
  commentId: T:Microsoft.Windows.Management.Deployment.StagePackageOptions
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.StagePackageOptions.html
  name: StagePackageOptions
  nameWithType: StagePackageOptions
  fullName: Microsoft.Windows.Management.Deployment.StagePackageOptions
- uid: Microsoft.Windows.Management.Deployment.StubPackageOption
  commentId: T:Microsoft.Windows.Management.Deployment.StubPackageOption
  parent: Microsoft.Windows.Management.Deployment
  href: Microsoft.Windows.Management.Deployment.StubPackageOption.html
  name: StubPackageOption
  nameWithType: StubPackageOption
  fullName: Microsoft.Windows.Management.Deployment.StubPackageOption
- uid: Microsoft.Windows.Management.Deployment
  commentId: N:Microsoft.Windows.Management.Deployment
  href: Microsoft.html
  name: Microsoft.Windows.Management.Deployment
  nameWithType: Microsoft.Windows.Management.Deployment
  fullName: Microsoft.Windows.Management.Deployment
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Windows
    name: Windows
    href: Microsoft.Windows.html
  - name: .
  - uid: Microsoft.Windows.Management
    name: Management
    href: Microsoft.Windows.Management.html
  - name: .
  - uid: Microsoft.Windows.Management.Deployment
    name: Deployment
    href: Microsoft.Windows.Management.Deployment.html
