### YamlMime:ManagedReference
items:
- uid: Microsoft.UI.Composition.CompositionGetValueStatus
  commentId: T:Microsoft.UI.Composition.CompositionGetValueStatus
  id: CompositionGetValueStatus
  parent: Microsoft.UI.Composition
  children:
  - Microsoft.UI.Composition.CompositionGetValueStatus.NotFound
  - Microsoft.UI.Composition.CompositionGetValueStatus.Succeeded
  - Microsoft.UI.Composition.CompositionGetValueStatus.TypeMismatch
  langs:
  - csharp
  - vb
  name: CompositionGetValueStatus
  nameWithType: CompositionGetValueStatus
  fullName: Microsoft.UI.Composition.CompositionGetValueStatus
  type: Enum
  source:
    remote:
      path: src/Microsoft.UI.Composition.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: CompositionGetValueStatus
    path: ../src/Microsoft.UI.Composition.cs
    startLine: 2901
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Composition
  syntax:
    content: >-
      [WindowsRuntimeType("Microsoft.UI")]

      [WinRTExposedType(typeof(EnumTypeDetails<CompositionGetValueStatus>))]

      [ContractVersion(typeof(WindowsAppSDKContract), 65536)]

      public enum CompositionGetValueStatus
    content.vb: >-
      <WindowsRuntimeType("Microsoft.UI")>

      <WinRTExposedType(GetType(EnumTypeDetails(Of CompositionGetValueStatus)))>

      <ContractVersion(GetType(WindowsAppSDKContract), 65536)>

      Public Enum CompositionGetValueStatus
  attributes:
  - type: WinRT.WindowsRuntimeTypeAttribute
    ctor: WinRT.WindowsRuntimeTypeAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Microsoft.UI
  - type: WinRT.WinRTExposedTypeAttribute
    ctor: WinRT.WinRTExposedTypeAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: WinRT.EnumTypeDetails{Microsoft.UI.Composition.CompositionGetValueStatus}
  - type: Windows.Foundation.Metadata.ContractVersionAttribute
    ctor: Windows.Foundation.Metadata.ContractVersionAttribute.#ctor(System.Type,System.UInt32)
    arguments:
    - type: System.Type
      value: Microsoft.Foundation.WindowsAppSDKContract
    - type: System.UInt32
      value: "65536"
- uid: Microsoft.UI.Composition.CompositionGetValueStatus.Succeeded
  commentId: F:Microsoft.UI.Composition.CompositionGetValueStatus.Succeeded
  id: Succeeded
  parent: Microsoft.UI.Composition.CompositionGetValueStatus
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: CompositionGetValueStatus.Succeeded
  fullName: Microsoft.UI.Composition.CompositionGetValueStatus.Succeeded
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Composition.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: Succeeded
    path: ../src/Microsoft.UI.Composition.cs
    startLine: 2904
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Composition
  syntax:
    content: Succeeded = 0
    return:
      type: Microsoft.UI.Composition.CompositionGetValueStatus
- uid: Microsoft.UI.Composition.CompositionGetValueStatus.TypeMismatch
  commentId: F:Microsoft.UI.Composition.CompositionGetValueStatus.TypeMismatch
  id: TypeMismatch
  parent: Microsoft.UI.Composition.CompositionGetValueStatus
  langs:
  - csharp
  - vb
  name: TypeMismatch
  nameWithType: CompositionGetValueStatus.TypeMismatch
  fullName: Microsoft.UI.Composition.CompositionGetValueStatus.TypeMismatch
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Composition.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: TypeMismatch
    path: ../src/Microsoft.UI.Composition.cs
    startLine: 2905
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Composition
  syntax:
    content: TypeMismatch = 1
    return:
      type: Microsoft.UI.Composition.CompositionGetValueStatus
- uid: Microsoft.UI.Composition.CompositionGetValueStatus.NotFound
  commentId: F:Microsoft.UI.Composition.CompositionGetValueStatus.NotFound
  id: NotFound
  parent: Microsoft.UI.Composition.CompositionGetValueStatus
  langs:
  - csharp
  - vb
  name: NotFound
  nameWithType: CompositionGetValueStatus.NotFound
  fullName: Microsoft.UI.Composition.CompositionGetValueStatus.NotFound
  type: Field
  source:
    remote:
      path: src/Microsoft.UI.Composition.cs
      branch: main
      repo: https://github.com/DGP-Studio/Microsoft.WindowsAppSDK.Projection.git
    id: NotFound
    path: ../src/Microsoft.UI.Composition.cs
    startLine: 2906
  assemblies:
  - Microsoft.WindowsAppSDK.Projection
  namespace: Microsoft.UI.Composition
  syntax:
    content: NotFound = 2
    return:
      type: Microsoft.UI.Composition.CompositionGetValueStatus
references:
- uid: Microsoft.UI.Composition
  commentId: N:Microsoft.UI.Composition
  href: Microsoft.html
  name: Microsoft.UI.Composition
  nameWithType: Microsoft.UI.Composition
  fullName: Microsoft.UI.Composition
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Composition
    name: Composition
    href: Microsoft.UI.Composition.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    href: Microsoft.html
  - name: .
  - uid: Microsoft.UI
    name: UI
    href: Microsoft.UI.html
  - name: .
  - uid: Microsoft.UI.Composition
    name: Composition
    href: Microsoft.UI.Composition.html
- uid: Microsoft.UI.Composition.CompositionGetValueStatus
  commentId: T:Microsoft.UI.Composition.CompositionGetValueStatus
  parent: Microsoft.UI.Composition
  href: Microsoft.UI.Composition.CompositionGetValueStatus.html
  name: CompositionGetValueStatus
  nameWithType: CompositionGetValueStatus
  fullName: Microsoft.UI.Composition.CompositionGetValueStatus
