//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.3.0-prerelease.250720.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using WinRT;
using WinRT.Interop;


#pragma warning disable 0169 // warning CS0169: The field '...' is never used
#pragma warning disable 0649 // warning CS0169: Field '...' is never assigned to
#pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213

namespace Microsoft.Windows.AI.ContentModerationInternal
{
    [global::Windows.Foundation.Metadata.ContractVersion(65536u)]
    public enum ContentModerationSessionContract
    {
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.AI.ContentModerationInternal")][Guid("1AFCEA00-B9DF-454A-B0E0-9C36B7A6FA2C")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession))]
    [global::Windows.Foundation.Metadata.ContractVersion(typeof(ImageContentModerationSessionContract), 65536u)]
    public interface IImageContentModerationSession : global::System.IDisposable
    {
        bool ValidateImage(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency);
        ImageContentAnalysisScores AnalyzeImage(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency);
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.AI.ContentModerationInternal")][Guid("E82A4CB1-A91E-5841-AB2F-8BA8FE241B5A")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSession))]
    [global::Windows.Foundation.Metadata.ContractVersion(typeof(TextBlockListContract), 65536u)]
    public interface ITextBlockListSession : global::System.IDisposable
    {
        bool IsTextBlocked(string query, string inputLanguage);
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.AI.ContentModerationInternal")][Guid("367F2388-6261-427E-B401-6289ADAB2F7D")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSession))]
    [global::Windows.Foundation.Metadata.ContractVersion(typeof(ContentModerationSessionContract), 65536u)]
    public interface ITextContentModerationSession : global::System.IDisposable
    {
        TextContentAnalysisScores AnalyzeText(string text, uint priority, uint frequency);
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.AI.ContentModerationInternal", "struct(Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores;u4;f4;f4;f4;f4;f4)")][global::WinRT.WindowsRuntimeHelperType][global::WinRT.WinRTExposedType(typeof(global::WinRT.StructTypeDetails<ImageContentAnalysisScores, ImageContentAnalysisScores>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(ImageContentModerationSessionContract), 65536u)]
    public struct ImageContentAnalysisScores: IEquatable<ImageContentAnalysisScores>
    {
        public uint numCategoryLevels;
        public float normalContentLevel;
        public float adultHarmContentLevel;
        public float racyContentLevel;
        public float goryContentLevel;
        public float violenceContentLevel;

        public ImageContentAnalysisScores(uint _numCategoryLevels, float _normalContentLevel, float _adultHarmContentLevel, float _racyContentLevel, float _goryContentLevel, float _violenceContentLevel)
        {
            numCategoryLevels = _numCategoryLevels; normalContentLevel = _normalContentLevel; adultHarmContentLevel = _adultHarmContentLevel; racyContentLevel = _racyContentLevel; goryContentLevel = _goryContentLevel; violenceContentLevel = _violenceContentLevel; 
        }

        public static bool operator ==(ImageContentAnalysisScores x, ImageContentAnalysisScores y) => x.numCategoryLevels == y.numCategoryLevels && x.normalContentLevel == y.normalContentLevel && x.adultHarmContentLevel == y.adultHarmContentLevel && x.racyContentLevel == y.racyContentLevel && x.goryContentLevel == y.goryContentLevel && x.violenceContentLevel == y.violenceContentLevel;
        public static bool operator !=(ImageContentAnalysisScores x, ImageContentAnalysisScores y) => !(x == y);
        public bool Equals(ImageContentAnalysisScores other) => this == other;
        public override bool Equals(object obj) => obj is ImageContentAnalysisScores that && this == that;
        public override int GetHashCode() => numCategoryLevels.GetHashCode() ^ normalContentLevel.GetHashCode() ^ adultHarmContentLevel.GetHashCode() ^ racyContentLevel.GetHashCode() ^ goryContentLevel.GetHashCode() ^ violenceContentLevel.GetHashCode();
    }
    [global::Windows.Foundation.Metadata.ContractVersion(65536u)]
    public enum ImageContentModerationSessionContract
    {
    }
    [global::Windows.Foundation.Metadata.ContractVersion(65536u)]
    public enum TextBlockListContract
    {
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.AI.ContentModerationInternal", "struct(Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores;u4;u4;u4;u4;u4)")][global::WinRT.WindowsRuntimeHelperType][global::WinRT.WinRTExposedType(typeof(global::WinRT.StructTypeDetails<TextContentAnalysisScores, TextContentAnalysisScores>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(ContentModerationSessionContract), 65536u)]
    public struct TextContentAnalysisScores: IEquatable<TextContentAnalysisScores>
    {
        public uint numCategoryLevels;
        public uint selfHarmContentLevel;
        public uint violentContentLevel;
        public uint hateContentLevel;
        public uint sexualContentLevel;

        public TextContentAnalysisScores(uint _numCategoryLevels, uint _selfHarmContentLevel, uint _violentContentLevel, uint _hateContentLevel, uint _sexualContentLevel)
        {
            numCategoryLevels = _numCategoryLevels; selfHarmContentLevel = _selfHarmContentLevel; violentContentLevel = _violentContentLevel; hateContentLevel = _hateContentLevel; sexualContentLevel = _sexualContentLevel; 
        }

        public static bool operator ==(TextContentAnalysisScores x, TextContentAnalysisScores y) => x.numCategoryLevels == y.numCategoryLevels && x.selfHarmContentLevel == y.selfHarmContentLevel && x.violentContentLevel == y.violentContentLevel && x.hateContentLevel == y.hateContentLevel && x.sexualContentLevel == y.sexualContentLevel;
        public static bool operator !=(TextContentAnalysisScores x, TextContentAnalysisScores y) => !(x == y);
        public bool Equals(TextContentAnalysisScores other) => this == other;
        public override bool Equals(object obj) => obj is TextContentAnalysisScores that && this == that;
        public override int GetHashCode() => numCategoryLevels.GetHashCode() ^ selfHarmContentLevel.GetHashCode() ^ violentContentLevel.GetHashCode() ^ hateContentLevel.GetHashCode() ^ sexualContentLevel.GetHashCode();
    }
}

#pragma warning disable CA1416
namespace ABI.Microsoft.Windows.AI.ContentModerationInternal
{
    public static class IImageContentModerationSessionMethods
    {


        public static unsafe bool ValidateImage(IObjectReference _obj, global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __inputImageBufferResource = default;
            byte __retval = default;
            try
            {
                __inputImageBufferResource = global::ABI.Microsoft.Windows.PrivateCommon.ImageBufferResource.CreateMarshaler2(inputImageBufferResource);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, byte*, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__inputImageBufferResource), priority, frequency, &__retval));
                global::System.GC.KeepAlive(_obj);
                return __retval != 0;
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__inputImageBufferResource);
            }
        }

        public static unsafe global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores AnalyzeImage(IObjectReference _obj, global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __inputImageBufferResource = default;
            global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores __retval = default;
            try
            {
                __inputImageBufferResource = global::ABI.Microsoft.Windows.PrivateCommon.ImageBufferResource.CreateMarshaler2(inputImageBufferResource);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores*, int>**)ThisPtr)[7](ThisPtr, MarshalInspectable<object>.GetAbi(__inputImageBufferResource), priority, frequency, &__retval));
                global::System.GC.KeepAlive(_obj);
                return __retval;
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__inputImageBufferResource);
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x0, 0xEA, 0xFC, 0x1A, 0xDF, 0xB9, 0x4A, 0x45, 0xB0, 0xE0, 0x9C, 0x36, 0xB7, 0xA6, 0xFA, 0x2C };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

        public static global::System.IntPtr AbiToProjectionVftablePtr => IImageContentModerationSession.AbiToProjectionVftablePtr;

    }
    [DynamicInterfaceCastableImplementation]
    [Guid("1AFCEA00-B9DF-454A-B0E0-9C36B7A6FA2C")]
    internal unsafe interface IImageContentModerationSession : global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession
    {

        public static readonly IntPtr AbiToProjectionVftablePtr;
        static unsafe IImageContentModerationSession()
        {
            AbiToProjectionVftablePtr = ComWrappersSupport.AllocateVtableMemory(typeof(IImageContentModerationSession), sizeof(IInspectable.Vftbl) + sizeof(IntPtr) * 2);
            *(IInspectable.Vftbl*)AbiToProjectionVftablePtr = IInspectable.Vftbl.AbiToProjectionVftable;
            ((delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, byte*, int>*)AbiToProjectionVftablePtr)[6] = &Do_Abi_ValidateImage_0;
            ((delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores*, int>*)AbiToProjectionVftablePtr)[7] = &Do_Abi_AnalyzeImage_1;
        }

        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_ValidateImage_0(IntPtr thisPtr, IntPtr inputImageBufferResource, uint priority, uint frequency, byte* result)
        {

            bool __result = default;

            *result = default;

            try
            {
                __result = global::WinRT.ComWrappersSupport.FindObject<global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession>(thisPtr).ValidateImage(global::ABI.Microsoft.Windows.PrivateCommon.ImageBufferResource.FromAbi(inputImageBufferResource), priority, frequency);
                *result = (byte)(__result ? 1 : 0);

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_AnalyzeImage_1(IntPtr thisPtr, IntPtr inputImageBufferResource, uint priority, uint frequency, global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores* result)
        {

            global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores __result = default;

            *result = default;

            try
            {
                __result = global::WinRT.ComWrappersSupport.FindObject<global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession>(thisPtr).AnalyzeImage(global::ABI.Microsoft.Windows.PrivateCommon.ImageBufferResource.FromAbi(inputImageBufferResource), priority, frequency);
                *result = __result;

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }

        unsafe bool global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession.ValidateImage(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency)
        {
            var _obj = ((IObjectReference)((IWinRTObject)this).GetObjectReferenceForType(typeof(global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession).TypeHandle));
            return global::ABI.Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSessionMethods.ValidateImage(_obj, inputImageBufferResource, priority, frequency);
        }

        unsafe global::Microsoft.Windows.AI.ContentModerationInternal.ImageContentAnalysisScores global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession.AnalyzeImage(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency)
        {
            var _obj = ((IObjectReference)((IWinRTObject)this).GetObjectReferenceForType(typeof(global::Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSession).TypeHandle));
            return global::ABI.Microsoft.Windows.AI.ContentModerationInternal.IImageContentModerationSessionMethods.AnalyzeImage(_obj, inputImageBufferResource, priority, frequency);
        }

        void global::System.IDisposable.Dispose() => ((global::System.IDisposable)(IWinRTObject)this).Dispose();
    }

    public static class ITextBlockListSessionMethods
    {


        public static unsafe bool IsTextBlocked(IObjectReference _obj, string query, string inputLanguage)
        {
            var ThisPtr = _obj.ThisPtr;

            byte __retval = default;
            MarshalString.Pinnable __query = new(query);
            MarshalString.Pinnable __inputLanguage = new(inputLanguage);
            fixed(void* ___query = __query, ___inputLanguage = __inputLanguage)
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr, byte*, int>**)ThisPtr)[6](ThisPtr, MarshalString.GetAbi(ref __query), MarshalString.GetAbi(ref __inputLanguage), &__retval));
                global::System.GC.KeepAlive(_obj);
                return __retval != 0;
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0xB1, 0x4C, 0x2A, 0xE8, 0x1E, 0xA9, 0x41, 0x58, 0xAB, 0x2F, 0x8B, 0xA8, 0xFE, 0x24, 0x1B, 0x5A };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

        public static global::System.IntPtr AbiToProjectionVftablePtr => ITextBlockListSession.AbiToProjectionVftablePtr;

    }
    [DynamicInterfaceCastableImplementation]
    [Guid("E82A4CB1-A91E-5841-AB2F-8BA8FE241B5A")]
    internal unsafe interface ITextBlockListSession : global::Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSession
    {

        public static readonly IntPtr AbiToProjectionVftablePtr;
        static unsafe ITextBlockListSession()
        {
            AbiToProjectionVftablePtr = ComWrappersSupport.AllocateVtableMemory(typeof(ITextBlockListSession), sizeof(IInspectable.Vftbl) + sizeof(IntPtr) * 1);
            *(IInspectable.Vftbl*)AbiToProjectionVftablePtr = IInspectable.Vftbl.AbiToProjectionVftable;
            ((delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr, byte*, int>*)AbiToProjectionVftablePtr)[6] = &Do_Abi_IsTextBlocked_0;
        }

        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_IsTextBlocked_0(IntPtr thisPtr, IntPtr query, IntPtr inputLanguage, byte* result)
        {

            bool __result = default;

            *result = default;

            try
            {
                __result = global::WinRT.ComWrappersSupport.FindObject<global::Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSession>(thisPtr).IsTextBlocked(MarshalString.FromAbi(query), MarshalString.FromAbi(inputLanguage));
                *result = (byte)(__result ? 1 : 0);

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }

        unsafe bool global::Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSession.IsTextBlocked(string query, string inputLanguage)
        {
            var _obj = ((IObjectReference)((IWinRTObject)this).GetObjectReferenceForType(typeof(global::Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSession).TypeHandle));
            return global::ABI.Microsoft.Windows.AI.ContentModerationInternal.ITextBlockListSessionMethods.IsTextBlocked(_obj, query, inputLanguage);
        }

        void global::System.IDisposable.Dispose() => ((global::System.IDisposable)(IWinRTObject)this).Dispose();
    }

    public static class ITextContentModerationSessionMethods
    {


        public static unsafe global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores AnalyzeText(IObjectReference _obj, string text, uint priority, uint frequency)
        {
            var ThisPtr = _obj.ThisPtr;

            global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores __retval = default;
            MarshalString.Pinnable __text = new(text);
            fixed(void* ___text = __text)
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores*, int>**)ThisPtr)[6](ThisPtr, MarshalString.GetAbi(ref __text), priority, frequency, &__retval));
                global::System.GC.KeepAlive(_obj);
                return __retval;
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x88, 0x23, 0x7F, 0x36, 0x61, 0x62, 0x7E, 0x42, 0xB4, 0x1, 0x62, 0x89, 0xAD, 0xAB, 0x2F, 0x7D };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

        public static global::System.IntPtr AbiToProjectionVftablePtr => ITextContentModerationSession.AbiToProjectionVftablePtr;

    }
    [DynamicInterfaceCastableImplementation]
    [Guid("367F2388-6261-427E-B401-6289ADAB2F7D")]
    internal unsafe interface ITextContentModerationSession : global::Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSession
    {

        public static readonly IntPtr AbiToProjectionVftablePtr;
        static unsafe ITextContentModerationSession()
        {
            AbiToProjectionVftablePtr = ComWrappersSupport.AllocateVtableMemory(typeof(ITextContentModerationSession), sizeof(IInspectable.Vftbl) + sizeof(IntPtr) * 1);
            *(IInspectable.Vftbl*)AbiToProjectionVftablePtr = IInspectable.Vftbl.AbiToProjectionVftable;
            ((delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint, uint, global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores*, int>*)AbiToProjectionVftablePtr)[6] = &Do_Abi_AnalyzeText_0;
        }

        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_AnalyzeText_0(IntPtr thisPtr, IntPtr text, uint priority, uint frequency, global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores* result)
        {

            global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores __result = default;

            *result = default;

            try
            {
                __result = global::WinRT.ComWrappersSupport.FindObject<global::Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSession>(thisPtr).AnalyzeText(MarshalString.FromAbi(text), priority, frequency);
                *result = __result;

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }

        unsafe global::Microsoft.Windows.AI.ContentModerationInternal.TextContentAnalysisScores global::Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSession.AnalyzeText(string text, uint priority, uint frequency)
        {
            var _obj = ((IObjectReference)((IWinRTObject)this).GetObjectReferenceForType(typeof(global::Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSession).TypeHandle));
            return global::ABI.Microsoft.Windows.AI.ContentModerationInternal.ITextContentModerationSessionMethods.AnalyzeText(_obj, text, priority, frequency);
        }

        void global::System.IDisposable.Dispose() => ((global::System.IDisposable)(IWinRTObject)this).Dispose();
    }

}
#pragma warning restore CA1416
