//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.3.0-prerelease.250720.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using WinRT;
using WinRT.Interop;


#pragma warning disable 0169 // warning CS0169: The field '...' is never used
#pragma warning disable 0649 // warning CS0169: Field '...' is never assigned to
#pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213

namespace Microsoft.Windows.Internal.Vision
{
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.Internal.Vision")]
    [global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.Internal.Vision.RecognizedTextInternal))]
    [global::ABI.Microsoft.Windows.Internal.Vision.RecognizedTextInternalRcwFactory]
    [global::WinRT.ProjectedRuntimeClass(typeof(global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal))]
    public sealed class RecognizedTextInternal : global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal, global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<RecognizedTextInternal>
    {
        private IntPtr ThisPtr => _inner == null ? (((IWinRTObject)this).NativeObject).ThisPtr : _inner.ThisPtr;

        private readonly IObjectReference _inner = null;



        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_IRecognizedTextInternal => _inner;


        public static RecognizedTextInternal FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) return null;
            return MarshalInspectable<RecognizedTextInternal>.FromAbi(thisPtr);
        }

        internal RecognizedTextInternal(IObjectReference objRef)
        {
            _inner = objRef.As(global::ABI.Microsoft.Windows.VisionInternal.IRecognizedTextInternalMethods.IID);

        }


        public static bool operator ==(RecognizedTextInternal x, RecognizedTextInternal y) => (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        public static bool operator !=(RecognizedTextInternal x, RecognizedTextInternal y) => !(x == y);
        public bool Equals(RecognizedTextInternal other) => this == other;
        public override bool Equals(object obj) => obj is RecognizedTextInternal that && this == that;
        public override int GetHashCode() => ThisPtr.GetHashCode();


        bool IWinRTObject.HasUnwrappableNativeObject => true;
        IObjectReference IWinRTObject.NativeObject => _inner;
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _queryInterfaceCache, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null); 
            return _queryInterfaceCache;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _additionalTypeData, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object>(), null); 
            return _additionalTypeData;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

        private struct InterfaceTag<I>{};


        public uint GetDataLength() => global::ABI.Microsoft.Windows.VisionInternal.IRecognizedTextInternalMethods.GetDataLength(_objRef_global__Microsoft_Windows_VisionInternal_IRecognizedTextInternal);

        public void GetData(byte[] buffer) => global::ABI.Microsoft.Windows.VisionInternal.IRecognizedTextInternalMethods.GetData(_objRef_global__Microsoft_Windows_VisionInternal_IRecognizedTextInternal, buffer);

        private bool IsOverridableInterface(Guid iid) => false;

        global::System.Runtime.InteropServices.CustomQueryInterfaceResult global::System.Runtime.InteropServices.ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || global::WinRT.Interop.IID.IID_IInspectable == iid || global::WinRT.Interop.IID.IID_IWeakReferenceSource == iid)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.Handled;
            }

            return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
        }
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.Internal.Vision")]
    [global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession))]
    [global::ABI.Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSessionRcwFactory]
    [global::WinRT.ProjectedRuntimeClass(typeof(global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4))]
    public sealed class ScreenRegionDetectorSession : global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4, global::System.IDisposable, global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession3, global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession, global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession2, global::Microsoft.Windows.PrivateCommon.IAnchorInstance, global::Microsoft.Windows.PrivateCommon.IGetSessionHostProcessId, global::Microsoft.Windows.PrivateCommon.IModelManager3, global::Microsoft.Windows.PrivateCommon.IModelManager, global::Microsoft.Windows.PrivateCommon.IModelManager2, global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<ScreenRegionDetectorSession>
    {
        private IntPtr ThisPtr => _inner == null ? (((IWinRTObject)this).NativeObject).ThisPtr : _inner.ThisPtr;

        private readonly IObjectReference _inner = null;



        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession4 => _inner;
        private volatile IObjectReference ___objRef_global__System_IDisposable;
        private IObjectReference Make___objRef_global__System_IDisposable()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__System_IDisposable, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.System.IDisposableMethods.IID), null);
            return ___objRef_global__System_IDisposable;
        }
        private IObjectReference _objRef_global__System_IDisposable => ___objRef_global__System_IDisposable ?? Make___objRef_global__System_IDisposable();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3;
        private IObjectReference Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession3Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3 => ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3 ?? Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession;
        private IObjectReference Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSessionMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession => ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession ?? Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2;
        private IObjectReference Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession2Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2 => ___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2 ?? Make___objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IAnchorInstanceMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance => ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IGetSessionHostProcessIdMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId => ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3 => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3 ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManager2Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2 => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2 ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2();



        private static volatile IObjectReference ___objRef_global__Microsoft_Windows_Internal_Vision_ScreenRegionDetectorSession;
        private static IObjectReference _objRef_global__Microsoft_Windows_Internal_Vision_ScreenRegionDetectorSession
        {
            get
            { 
                var factory = ___objRef_global__Microsoft_Windows_Internal_Vision_ScreenRegionDetectorSession;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Microsoft_Windows_Internal_Vision_ScreenRegionDetectorSession = ActivationFactory.Get("Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession");
                }
            }
        }

        public ScreenRegionDetectorSession() 
        {
            _inner = global::ABI.WinRT.Interop.IActivationFactoryMethods.ActivateInstanceUnsafe(_objRef_global__Microsoft_Windows_Internal_Vision_ScreenRegionDetectorSession, global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4Methods.IID);
            ComWrappersSupport.RegisterObjectForInterface(this, ThisPtr);
            ComWrappersHelper.Init(_inner, false);

        }

        public static ScreenRegionDetectorSession FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) return null;
            return MarshalInspectable<ScreenRegionDetectorSession>.FromAbi(thisPtr);
        }

        internal ScreenRegionDetectorSession(IObjectReference objRef)
        {
            _inner = objRef.As(global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4Methods.IID);

        }


        public static bool operator ==(ScreenRegionDetectorSession x, ScreenRegionDetectorSession y) => (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        public static bool operator !=(ScreenRegionDetectorSession x, ScreenRegionDetectorSession y) => !(x == y);
        public bool Equals(ScreenRegionDetectorSession other) => this == other;
        public override bool Equals(object obj) => obj is ScreenRegionDetectorSession that && this == that;
        public override int GetHashCode() => ThisPtr.GetHashCode();


        bool IWinRTObject.HasUnwrappableNativeObject => true;
        IObjectReference IWinRTObject.NativeObject => _inner;
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _queryInterfaceCache, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null); 
            return _queryInterfaceCache;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _additionalTypeData, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object>(), null); 
            return _additionalTypeData;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

        private struct InterfaceTag<I>{};


        public global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Windows.VisionInternal.ScreenRegionInternal4> GetScreenRegions4(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency) => global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4Methods.GetScreenRegions4(_objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession4, inputImageBufferResource, priority, frequency);

        public void Dispose() => global::ABI.System.IDisposableMethods.Dispose(_objRef_global__System_IDisposable);

        public global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Windows.VisionInternal.ScreenRegionInternal> GetScreenRegions(global::Microsoft.Windows.PrivateCommon.ImageBufferResource inputImageBufferResource, uint priority, uint frequency) => global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession3Methods.GetScreenRegions(_objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession3, inputImageBufferResource, priority, frequency);

        public global::Windows.Foundation.IAsyncOperation<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Windows.VisionInternal.ScreenRegionInternal>> GetScreenRegionsAsync(global::Microsoft.Windows.PrivateCommon.ImageBufferView inputImageBufferView, global::Microsoft.Windows.PrivateCommon.ImageBufferViewData inputImageBufferViewData) => global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSessionMethods.GetScreenRegionsAsync(_objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession, inputImageBufferView, inputImageBufferViewData);

        public global::Windows.Foundation.IAsyncOperation<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Windows.VisionInternal.ScreenRegionInternal>> GetScreenRegionsAsync(global::Microsoft.Windows.PrivateCommon.ImageBufferView inputImageBufferView, global::Microsoft.Windows.PrivateCommon.ImageBufferViewData inputImageBufferViewData, uint priority, uint frequency) => global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession2Methods.GetScreenRegionsAsync(_objRef_global__Microsoft_Windows_VisionInternal_IScreenRegionDetectorSession2, inputImageBufferView, inputImageBufferViewData, priority, frequency);

        public void AnchorInstance(object instance) => global::ABI.Microsoft.Windows.PrivateCommon.IAnchorInstanceMethods.AnchorInstance(_objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance, instance);

        public uint GetSessionHostProcessId() => global::ABI.Microsoft.Windows.PrivateCommon.IGetSessionHostProcessIdMethods.GetSessionHostProcessId(_objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId);

        public void GenerateCacheModel() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.GenerateCacheModel(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3);

        public void SetCorrelationVector(string correlationVector) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.SetCorrelationVector(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3, correlationVector);

        public bool IsModelCacheReady() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.IsModelCacheReady(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3);

        public void EnsureModelInitialized() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.EnsureModelInitialized(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager);

        public void GenerateCacheModel(string offlineDriverPath) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.GenerateCacheModel(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager, offlineDriverPath);

        public void SetPackageFamilyName(string packageFamilyName) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager2Methods.SetPackageFamilyName(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2, packageFamilyName);

        private bool IsOverridableInterface(Guid iid) => false;

        global::System.Runtime.InteropServices.CustomQueryInterfaceResult global::System.Runtime.InteropServices.ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || global::WinRT.Interop.IID.IID_IInspectable == iid || global::WinRT.Interop.IID.IID_IWeakReferenceSource == iid)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.Handled;
            }

            return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
        }
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Windows.Internal.Vision")]
    [global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Microsoft.Windows.Internal.Vision.TextRecognizerSession))]
    [global::ABI.Microsoft.Windows.Internal.Vision.TextRecognizerSessionRcwFactory]
    [global::WinRT.ProjectedRuntimeClass(typeof(global::Microsoft.Windows.VisionInternal.ITextRecognizerSession3))]
    public sealed class TextRecognizerSession : global::Microsoft.Windows.VisionInternal.ITextRecognizerSession3, global::System.IDisposable, global::Microsoft.Windows.VisionInternal.ITextRecognizerSession, global::Microsoft.Windows.VisionInternal.ITextRecognizerSession2, global::Microsoft.Windows.PrivateCommon.IAnchorInstance, global::Microsoft.Windows.PrivateCommon.IGetSessionHostProcessId, global::Microsoft.Windows.PrivateCommon.IModelManager3, global::Microsoft.Windows.PrivateCommon.IModelManager, global::Microsoft.Windows.PrivateCommon.IModelManager2, global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<TextRecognizerSession>
    {
        private IntPtr ThisPtr => _inner == null ? (((IWinRTObject)this).NativeObject).ThisPtr : _inner.ThisPtr;

        private readonly IObjectReference _inner = null;



        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession3 => _inner;
        private volatile IObjectReference ___objRef_global__System_IDisposable;
        private IObjectReference Make___objRef_global__System_IDisposable()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__System_IDisposable, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.System.IDisposableMethods.IID), null);
            return ___objRef_global__System_IDisposable;
        }
        private IObjectReference _objRef_global__System_IDisposable => ___objRef_global__System_IDisposable ?? Make___objRef_global__System_IDisposable();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession;
        private IObjectReference Make___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSessionMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession => ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession ?? Make___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2;
        private IObjectReference Make___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession2Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2 => ___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2 ?? Make___objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IAnchorInstanceMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance => ___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IGetSessionHostProcessIdMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId => ___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3 => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3 ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager();

        private volatile IObjectReference ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2;
        private IObjectReference Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2()
        {
            global::System.Threading.Interlocked.CompareExchange(ref ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(global::ABI.Microsoft.Windows.PrivateCommon.IModelManager2Methods.IID), null);
            return ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2;
        }
        private IObjectReference _objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2 => ___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2 ?? Make___objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2();



        private static volatile IObjectReference ___objRef_global__Microsoft_Windows_Internal_Vision_TextRecognizerSession;
        private static IObjectReference _objRef_global__Microsoft_Windows_Internal_Vision_TextRecognizerSession
        {
            get
            { 
                var factory = ___objRef_global__Microsoft_Windows_Internal_Vision_TextRecognizerSession;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Microsoft_Windows_Internal_Vision_TextRecognizerSession = ActivationFactory.Get("Microsoft.Windows.Internal.Vision.TextRecognizerSession");
                }
            }
        }

        public TextRecognizerSession() 
        {
            _inner = global::ABI.WinRT.Interop.IActivationFactoryMethods.ActivateInstanceUnsafe(_objRef_global__Microsoft_Windows_Internal_Vision_TextRecognizerSession, global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession3Methods.IID);
            ComWrappersSupport.RegisterObjectForInterface(this, ThisPtr);
            ComWrappersHelper.Init(_inner, false);

        }

        public static TextRecognizerSession FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) return null;
            return MarshalInspectable<TextRecognizerSession>.FromAbi(thisPtr);
        }

        internal TextRecognizerSession(IObjectReference objRef)
        {
            _inner = objRef.As(global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession3Methods.IID);

        }


        public static bool operator ==(TextRecognizerSession x, TextRecognizerSession y) => (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        public static bool operator !=(TextRecognizerSession x, TextRecognizerSession y) => !(x == y);
        public bool Equals(TextRecognizerSession other) => this == other;
        public override bool Equals(object obj) => obj is TextRecognizerSession that && this == that;
        public override int GetHashCode() => ThisPtr.GetHashCode();


        bool IWinRTObject.HasUnwrappableNativeObject => true;
        IObjectReference IWinRTObject.NativeObject => _inner;
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _queryInterfaceCache, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null); 
            return _queryInterfaceCache;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _additionalTypeData, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object>(), null); 
            return _additionalTypeData;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

        private struct InterfaceTag<I>{};


        public global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal RecognizeTextFromImage(global::Microsoft.Windows.PrivateCommon.ImageBufferResource imageBufferResource, global::Microsoft.Windows.VisionInternal.TextRecognizerOptionsInternal options, uint priority, uint frequency) => global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession3Methods.RecognizeTextFromImage(_objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession3, imageBufferResource, options, priority, frequency);

        public void Dispose() => global::ABI.System.IDisposableMethods.Dispose(_objRef_global__System_IDisposable);

        public global::Windows.Foundation.IAsyncOperation<global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal> RecognizeTextFromImageAsync(global::Microsoft.Windows.PrivateCommon.ImageBufferView imageBufferView, global::Microsoft.Windows.PrivateCommon.ImageBufferViewData imageBufferViewData, global::Microsoft.Windows.VisionInternal.TextRecognizerOptionsInternal options) => global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSessionMethods.RecognizeTextFromImageAsync(_objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession, imageBufferView, imageBufferViewData, options);

        public global::Windows.Foundation.IAsyncOperation<global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal> RecognizeTextFromImageAsync(global::Microsoft.Windows.PrivateCommon.ImageBufferView imageBufferView, global::Microsoft.Windows.PrivateCommon.ImageBufferViewData imageBufferViewData, global::Microsoft.Windows.VisionInternal.TextRecognizerOptionsInternal options, uint priority, uint frequency) => global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession2Methods.RecognizeTextFromImageAsync(_objRef_global__Microsoft_Windows_VisionInternal_ITextRecognizerSession2, imageBufferView, imageBufferViewData, options, priority, frequency);

        public void AnchorInstance(object instance) => global::ABI.Microsoft.Windows.PrivateCommon.IAnchorInstanceMethods.AnchorInstance(_objRef_global__Microsoft_Windows_PrivateCommon_IAnchorInstance, instance);

        public uint GetSessionHostProcessId() => global::ABI.Microsoft.Windows.PrivateCommon.IGetSessionHostProcessIdMethods.GetSessionHostProcessId(_objRef_global__Microsoft_Windows_PrivateCommon_IGetSessionHostProcessId);

        public void GenerateCacheModel() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.GenerateCacheModel(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3);

        public void SetCorrelationVector(string correlationVector) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.SetCorrelationVector(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3, correlationVector);

        public bool IsModelCacheReady() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager3Methods.IsModelCacheReady(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager3);

        public void EnsureModelInitialized() => global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.EnsureModelInitialized(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager);

        public void GenerateCacheModel(string offlineDriverPath) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManagerMethods.GenerateCacheModel(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager, offlineDriverPath);

        public void SetPackageFamilyName(string packageFamilyName) => global::ABI.Microsoft.Windows.PrivateCommon.IModelManager2Methods.SetPackageFamilyName(_objRef_global__Microsoft_Windows_PrivateCommon_IModelManager2, packageFamilyName);

        private bool IsOverridableInterface(Guid iid) => false;

        global::System.Runtime.InteropServices.CustomQueryInterfaceResult global::System.Runtime.InteropServices.ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || global::WinRT.Interop.IID.IID_IInspectable == iid || global::WinRT.Interop.IID.IID_IWeakReferenceSource == iid)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.Handled;
            }

            return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
        }
    }
}

#pragma warning disable CA1416
namespace ABI.Microsoft.Windows.Internal.Vision
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public struct RecognizedTextInternal
    {

        public static IObjectReference CreateMarshaler(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal obj) => obj is null ? null : MarshalInterface<global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal>.CreateMarshaler(obj);
        public static ObjectReferenceValue CreateMarshaler2(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal obj) => MarshalInterface<global::Microsoft.Windows.VisionInternal.IRecognizedTextInternal>.CreateMarshaler2(obj, global::ABI.Microsoft.Windows.VisionInternal.IRecognizedTextInternalMethods.IID);
        public static IntPtr GetAbi(IObjectReference value) => value is null ? IntPtr.Zero : MarshalInterfaceHelper<object>.GetAbi(value);
        public static global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal FromAbi(IntPtr thisPtr) => global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal.FromAbi(thisPtr);
        public static IntPtr FromManaged(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal obj) => obj is null ? IntPtr.Zero : CreateMarshaler2(obj).Detach();
        public static unsafe MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.MarshalerArray CreateMarshalerArray(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.CreateMarshalerArray2(array, (o) => CreateMarshaler2(o));
        public static (int length, IntPtr data) GetAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.GetAbiArray(box);
        public static unsafe global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal[] FromAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.FromAbiArray(box, FromAbi);
        public static void CopyAbiArray(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal[] array, object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.CopyAbiArray(array, box, FromAbi);
        public static (int length, IntPtr data) FromManagedArray(global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.FromManagedArray(array, (o) => FromManaged(o));
        public static void DisposeMarshaler(IObjectReference value) => MarshalInspectable<object>.DisposeMarshaler(value);
        public static void DisposeMarshalerArray(MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.MarshalerArray array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal>.DisposeMarshalerArray(array);
        public static void DisposeAbi(IntPtr abi) => MarshalInspectable<object>.DisposeAbi(abi);
        public static unsafe void DisposeAbiArray(object box) => MarshalInspectable<object>.DisposeAbiArray(box);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class RecognizedTextInternalRcwFactoryAttribute : global::WinRT.WinRTImplementationTypeRcwFactoryAttribute
    {
        public override object CreateInstance(global::WinRT.IInspectable inspectable)
            => new global::Microsoft.Windows.Internal.Vision.RecognizedTextInternal(inspectable.ObjRef);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public struct ScreenRegionDetectorSession
    {

        public static IObjectReference CreateMarshaler(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession obj) => obj is null ? null : MarshalInterface<global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4>.CreateMarshaler(obj);
        public static ObjectReferenceValue CreateMarshaler2(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession obj) => MarshalInterface<global::Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4>.CreateMarshaler2(obj, global::ABI.Microsoft.Windows.VisionInternal.IScreenRegionDetectorSession4Methods.IID);
        public static IntPtr GetAbi(IObjectReference value) => value is null ? IntPtr.Zero : MarshalInterfaceHelper<object>.GetAbi(value);
        public static global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession FromAbi(IntPtr thisPtr) => global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession.FromAbi(thisPtr);
        public static IntPtr FromManaged(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession obj) => obj is null ? IntPtr.Zero : CreateMarshaler2(obj).Detach();
        public static unsafe MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.MarshalerArray CreateMarshalerArray(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.CreateMarshalerArray2(array, (o) => CreateMarshaler2(o));
        public static (int length, IntPtr data) GetAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.GetAbiArray(box);
        public static unsafe global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession[] FromAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.FromAbiArray(box, FromAbi);
        public static void CopyAbiArray(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession[] array, object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.CopyAbiArray(array, box, FromAbi);
        public static (int length, IntPtr data) FromManagedArray(global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.FromManagedArray(array, (o) => FromManaged(o));
        public static void DisposeMarshaler(IObjectReference value) => MarshalInspectable<object>.DisposeMarshaler(value);
        public static void DisposeMarshalerArray(MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.MarshalerArray array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession>.DisposeMarshalerArray(array);
        public static void DisposeAbi(IntPtr abi) => MarshalInspectable<object>.DisposeAbi(abi);
        public static unsafe void DisposeAbiArray(object box) => MarshalInspectable<object>.DisposeAbiArray(box);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class ScreenRegionDetectorSessionRcwFactoryAttribute : global::WinRT.WinRTImplementationTypeRcwFactoryAttribute
    {
        public override object CreateInstance(global::WinRT.IInspectable inspectable)
            => new global::Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession(inspectable.ObjRef);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public struct TextRecognizerSession
    {

        public static IObjectReference CreateMarshaler(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession obj) => obj is null ? null : MarshalInterface<global::Microsoft.Windows.VisionInternal.ITextRecognizerSession3>.CreateMarshaler(obj);
        public static ObjectReferenceValue CreateMarshaler2(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession obj) => MarshalInterface<global::Microsoft.Windows.VisionInternal.ITextRecognizerSession3>.CreateMarshaler2(obj, global::ABI.Microsoft.Windows.VisionInternal.ITextRecognizerSession3Methods.IID);
        public static IntPtr GetAbi(IObjectReference value) => value is null ? IntPtr.Zero : MarshalInterfaceHelper<object>.GetAbi(value);
        public static global::Microsoft.Windows.Internal.Vision.TextRecognizerSession FromAbi(IntPtr thisPtr) => global::Microsoft.Windows.Internal.Vision.TextRecognizerSession.FromAbi(thisPtr);
        public static IntPtr FromManaged(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession obj) => obj is null ? IntPtr.Zero : CreateMarshaler2(obj).Detach();
        public static unsafe MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.MarshalerArray CreateMarshalerArray(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.CreateMarshalerArray2(array, (o) => CreateMarshaler2(o));
        public static (int length, IntPtr data) GetAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.GetAbiArray(box);
        public static unsafe global::Microsoft.Windows.Internal.Vision.TextRecognizerSession[] FromAbiArray(object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.FromAbiArray(box, FromAbi);
        public static void CopyAbiArray(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession[] array, object box) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.CopyAbiArray(array, box, FromAbi);
        public static (int length, IntPtr data) FromManagedArray(global::Microsoft.Windows.Internal.Vision.TextRecognizerSession[] array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.FromManagedArray(array, (o) => FromManaged(o));
        public static void DisposeMarshaler(IObjectReference value) => MarshalInspectable<object>.DisposeMarshaler(value);
        public static void DisposeMarshalerArray(MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.MarshalerArray array) => MarshalInterfaceHelper<global::Microsoft.Windows.Internal.Vision.TextRecognizerSession>.DisposeMarshalerArray(array);
        public static void DisposeAbi(IntPtr abi) => MarshalInspectable<object>.DisposeAbi(abi);
        public static unsafe void DisposeAbiArray(object box) => MarshalInspectable<object>.DisposeAbiArray(box);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class TextRecognizerSessionRcwFactoryAttribute : global::WinRT.WinRTImplementationTypeRcwFactoryAttribute
    {
        public override object CreateInstance(global::WinRT.IInspectable inspectable)
            => new global::Microsoft.Windows.Internal.Vision.TextRecognizerSession(inspectable.ObjRef);
    }
}
#pragma warning restore CA1416
