//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.2.0.241111.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using WinRT;
using WinRT.Interop;


#pragma warning disable 0169 // warning CS0169: The field '...' is never used
#pragma warning disable 0649 // warning CS0169: Field '...' is never assigned to
#pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213

namespace Microsoft.Graphics.DirectX
{
    [global::WinRT.WindowsRuntimeType("Microsoft.Graphics")][global::WinRT.WinRTExposedType(typeof(global::WinRT.EnumTypeDetails<DirectXAlphaMode>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(global::Microsoft.Foundation.WindowsAppSDKContract), 65536u)]
    public enum DirectXAlphaMode : int
    {
        Unspecified = unchecked((int)0),
        Premultiplied = unchecked((int)0x1),
        Straight = unchecked((int)0x2),
        Ignore = unchecked((int)0x3),
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Graphics")][global::WinRT.WinRTExposedType(typeof(global::WinRT.EnumTypeDetails<DirectXColorSpace>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(global::Microsoft.Foundation.WindowsAppSDKContract), 65536u)]
    public enum DirectXColorSpace : int
    {
        RgbFullG22NoneP709 = unchecked((int)0),
        RgbFullG10NoneP709 = unchecked((int)0x1),
        RgbStudioG22NoneP709 = unchecked((int)0x2),
        RgbStudioG22NoneP2020 = unchecked((int)0x3),
        Reserved = unchecked((int)0x4),
        YccFullG22NoneP709X601 = unchecked((int)0x5),
        YccStudioG22LeftP601 = unchecked((int)0x6),
        YccFullG22LeftP601 = unchecked((int)0x7),
        YccStudioG22LeftP709 = unchecked((int)0x8),
        YccFullG22LeftP709 = unchecked((int)0x9),
        YccStudioG22LeftP2020 = unchecked((int)0xa),
        YccFullG22LeftP2020 = unchecked((int)0xb),
        RgbFullG2084NoneP2020 = unchecked((int)0xc),
        YccStudioG2084LeftP2020 = unchecked((int)0xd),
        RgbStudioG2084NoneP2020 = unchecked((int)0xe),
        YccStudioG22TopLeftP2020 = unchecked((int)0xf),
        YccStudioG2084TopLeftP2020 = unchecked((int)0x10),
        RgbFullG22NoneP2020 = unchecked((int)0x11),
        YccStudioGHlgTopLeftP2020 = unchecked((int)0x12),
        YccFullGHlgTopLeftP2020 = unchecked((int)0x13),
        RgbStudioG24NoneP709 = unchecked((int)0x14),
        RgbStudioG24NoneP2020 = unchecked((int)0x15),
        YccStudioG24LeftP709 = unchecked((int)0x16),
        YccStudioG24LeftP2020 = unchecked((int)0x17),
        YccStudioG24TopLeftP2020 = unchecked((int)0x18),
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Graphics")][global::WinRT.WinRTExposedType(typeof(global::WinRT.EnumTypeDetails<DirectXPixelFormat>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(global::Microsoft.Foundation.WindowsAppSDKContract), 65536u)]
    public enum DirectXPixelFormat : int
    {
        Unknown = unchecked((int)0),
        R32G32B32A32Typeless = unchecked((int)0x1),
        R32G32B32A32Float = unchecked((int)0x2),
        R32G32B32A32UInt = unchecked((int)0x3),
        R32G32B32A32Int = unchecked((int)0x4),
        R32G32B32Typeless = unchecked((int)0x5),
        R32G32B32Float = unchecked((int)0x6),
        R32G32B32UInt = unchecked((int)0x7),
        R32G32B32Int = unchecked((int)0x8),
        R16G16B16A16Typeless = unchecked((int)0x9),
        R16G16B16A16Float = unchecked((int)0xa),
        R16G16B16A16UIntNormalized = unchecked((int)0xb),
        R16G16B16A16UInt = unchecked((int)0xc),
        R16G16B16A16IntNormalized = unchecked((int)0xd),
        R16G16B16A16Int = unchecked((int)0xe),
        R32G32Typeless = unchecked((int)0xf),
        R32G32Float = unchecked((int)0x10),
        R32G32UInt = unchecked((int)0x11),
        R32G32Int = unchecked((int)0x12),
        R32G8X24Typeless = unchecked((int)0x13),
        D32FloatS8X24UInt = unchecked((int)0x14),
        R32FloatX8X24Typeless = unchecked((int)0x15),
        X32TypelessG8X24UInt = unchecked((int)0x16),
        R10G10B10A2Typeless = unchecked((int)0x17),
        R10G10B10A2UIntNormalized = unchecked((int)0x18),
        R10G10B10A2UInt = unchecked((int)0x19),
        R11G11B10Float = unchecked((int)0x1a),
        R8G8B8A8Typeless = unchecked((int)0x1b),
        R8G8B8A8UIntNormalized = unchecked((int)0x1c),
        R8G8B8A8UIntNormalizedSrgb = unchecked((int)0x1d),
        R8G8B8A8UInt = unchecked((int)0x1e),
        R8G8B8A8IntNormalized = unchecked((int)0x1f),
        R8G8B8A8Int = unchecked((int)0x20),
        R16G16Typeless = unchecked((int)0x21),
        R16G16Float = unchecked((int)0x22),
        R16G16UIntNormalized = unchecked((int)0x23),
        R16G16UInt = unchecked((int)0x24),
        R16G16IntNormalized = unchecked((int)0x25),
        R16G16Int = unchecked((int)0x26),
        R32Typeless = unchecked((int)0x27),
        D32Float = unchecked((int)0x28),
        R32Float = unchecked((int)0x29),
        R32UInt = unchecked((int)0x2a),
        R32Int = unchecked((int)0x2b),
        R24G8Typeless = unchecked((int)0x2c),
        D24UIntNormalizedS8UInt = unchecked((int)0x2d),
        R24UIntNormalizedX8Typeless = unchecked((int)0x2e),
        X24TypelessG8UInt = unchecked((int)0x2f),
        R8G8Typeless = unchecked((int)0x30),
        R8G8UIntNormalized = unchecked((int)0x31),
        R8G8UInt = unchecked((int)0x32),
        R8G8IntNormalized = unchecked((int)0x33),
        R8G8Int = unchecked((int)0x34),
        R16Typeless = unchecked((int)0x35),
        R16Float = unchecked((int)0x36),
        D16UIntNormalized = unchecked((int)0x37),
        R16UIntNormalized = unchecked((int)0x38),
        R16UInt = unchecked((int)0x39),
        R16IntNormalized = unchecked((int)0x3a),
        R16Int = unchecked((int)0x3b),
        R8Typeless = unchecked((int)0x3c),
        R8UIntNormalized = unchecked((int)0x3d),
        R8UInt = unchecked((int)0x3e),
        R8IntNormalized = unchecked((int)0x3f),
        R8Int = unchecked((int)0x40),
        A8UIntNormalized = unchecked((int)0x41),
        R1UIntNormalized = unchecked((int)0x42),
        R9G9B9E5SharedExponent = unchecked((int)0x43),
        R8G8B8G8UIntNormalized = unchecked((int)0x44),
        G8R8G8B8UIntNormalized = unchecked((int)0x45),
        BC1Typeless = unchecked((int)0x46),
        BC1UIntNormalized = unchecked((int)0x47),
        BC1UIntNormalizedSrgb = unchecked((int)0x48),
        BC2Typeless = unchecked((int)0x49),
        BC2UIntNormalized = unchecked((int)0x4a),
        BC2UIntNormalizedSrgb = unchecked((int)0x4b),
        BC3Typeless = unchecked((int)0x4c),
        BC3UIntNormalized = unchecked((int)0x4d),
        BC3UIntNormalizedSrgb = unchecked((int)0x4e),
        BC4Typeless = unchecked((int)0x4f),
        BC4UIntNormalized = unchecked((int)0x50),
        BC4IntNormalized = unchecked((int)0x51),
        BC5Typeless = unchecked((int)0x52),
        BC5UIntNormalized = unchecked((int)0x53),
        BC5IntNormalized = unchecked((int)0x54),
        B5G6R5UIntNormalized = unchecked((int)0x55),
        B5G5R5A1UIntNormalized = unchecked((int)0x56),
        B8G8R8A8UIntNormalized = unchecked((int)0x57),
        B8G8R8X8UIntNormalized = unchecked((int)0x58),
        R10G10B10XRBiasA2UIntNormalized = unchecked((int)0x59),
        B8G8R8A8Typeless = unchecked((int)0x5a),
        B8G8R8A8UIntNormalizedSrgb = unchecked((int)0x5b),
        B8G8R8X8Typeless = unchecked((int)0x5c),
        B8G8R8X8UIntNormalizedSrgb = unchecked((int)0x5d),
        BC6HTypeless = unchecked((int)0x5e),
        BC6H16UnsignedFloat = unchecked((int)0x5f),
        BC6H16Float = unchecked((int)0x60),
        BC7Typeless = unchecked((int)0x61),
        BC7UIntNormalized = unchecked((int)0x62),
        BC7UIntNormalizedSrgb = unchecked((int)0x63),
        Ayuv = unchecked((int)0x64),
        Y410 = unchecked((int)0x65),
        Y416 = unchecked((int)0x66),
        NV12 = unchecked((int)0x67),
        P010 = unchecked((int)0x68),
        P016 = unchecked((int)0x69),
        Opaque420 = unchecked((int)0x6a),
        Yuy2 = unchecked((int)0x6b),
        Y210 = unchecked((int)0x6c),
        Y216 = unchecked((int)0x6d),
        NV11 = unchecked((int)0x6e),
        AI44 = unchecked((int)0x6f),
        IA44 = unchecked((int)0x70),
        P8 = unchecked((int)0x71),
        A8P8 = unchecked((int)0x72),
        B4G4R4A4UIntNormalized = unchecked((int)0x73),
        P208 = unchecked((int)0x82),
        V208 = unchecked((int)0x83),
        V408 = unchecked((int)0x84),
        SamplerFeedbackMinMipOpaque = unchecked((int)0xbd),
        SamplerFeedbackMipRegionUsedOpaque = unchecked((int)0xbe),
        A4B4G4R4 = unchecked((int)0xbf),
    }
    [global::WinRT.WindowsRuntimeType("Microsoft.Graphics")][global::WinRT.WinRTExposedType(typeof(global::WinRT.EnumTypeDetails<DirectXPrimitiveTopology>))][global::Windows.Foundation.Metadata.ContractVersion(typeof(global::Microsoft.Foundation.WindowsAppSDKContract), 65536u)]
    public enum DirectXPrimitiveTopology : int
    {
        Undefined = unchecked((int)0),
        PointList = unchecked((int)0x1),
        LineList = unchecked((int)0x2),
        LineStrip = unchecked((int)0x3),
        TriangleList = unchecked((int)0x4),
        TriangleStrip = unchecked((int)0x5),
    }
}
